### ISSUE TITLE
100% renewable (Urgenda) scenario has slight differences in primary demand between BETA and PRODUCTION

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2421] opened 2017-06-20 12:08 UTC
BETA
![image](https://user-images.githubusercontent.com/1303760/27332365-deb01236-55c1-11e7-8797-bc9123e75ebd.png)
 and PRODUCTION:
![image](https://user-images.githubusercontent.com/1303760/27332368-e8332ef6-55c1-11e7-807f-0da88605f49a.png)

**Comment by ChaelKruip** [comment] 2017-06-20 12:09
I opened both from the preset menu.

**Comment by antw** [comment] 2017-06-20 15:00
My local copy agrees with beta. Yet both beta and production are running identical ETEngine and ETSource versions. :confused:

**Comment by ChaelKruip** [comment] 2017-06-20 15:08
> My local copy agrees with beta. Yet both beta and production are running identical ETEngine and ETSource versions and have identical inputs.

Same Merit?

**Comment by antw** [comment] 2017-06-20 16:51
I found out why: we have many scenarios on beta which have been converted to presets, but the scenarios have not been removed from the database as they are on production.

The result is that beta is using the scenario instead of the preset. We _should_ delete these – as we do on production – but I'm not sure if they're still being used in some way? If so, we need to duplicate those that are and assign them a new ID.

| Scenario ID | Title | Updated at |
| :---: | --- | --- |
| [155680](https://beta-pro.energytransitionmodel.com/scenarios/155680) | Het kan als je wilt 98% duurzame energie in 2030 | 2013-06-12 10:02:14 | 2016-08-11 09:13:53 |
| [363119](https://beta-pro.energytransitionmodel.com/scenarios/363119) | BAU NL | 2016-08-11 09:18:32 |
| [363781](https://beta-pro.energytransitionmodel.com/scenarios/363781) | BAU EU27 | 2016-08-11 09:18:34 |
| [363789](https://beta-pro.energytransitionmodel.com/scenarios/363789) | BAU UK | 2016-08-11 09:18:34 |
| [363802](https://beta-pro.energytransitionmodel.com/scenarios/363802) | BAU PL | 2016-08-11 09:18:34 |
| [363816](https://beta-pro.energytransitionmodel.com/scenarios/363816) | BAU DE | 2016-08-11 09:18:34 |
| [363828](https://beta-pro.energytransitionmodel.com/scenarios/363828) | BAU ES | 2016-08-11 09:18:35 |
| [363831](https://beta-pro.energytransitionmodel.com/scenarios/363831) | BAU FR | 2016-08-11 09:18:35 |
| [363836](https://beta-pro.energytransitionmodel.com/scenarios/363836) | EE EU27 | 2016-08-11 09:18:35 |
| [363839](https://beta-pro.energytransitionmodel.com/scenarios/363839) | EE FR | 2016-08-11 09:18:35 |
| [363842](https://beta-pro.energytransitionmodel.com/scenarios/363842) | EE ES | 2016-08-11 09:18:35 |
| [363845](https://beta-pro.energytransitionmodel.com/scenarios/363845) | EE NL | 2016-08-11 09:18:35 |
| [363847](https://beta-pro.energytransitionmodel.com/scenarios/363847) | EE UK | 2016-08-11 09:18:35 |
| [363850](https://beta-pro.energytransitionmodel.com/scenarios/363850) | EE DE | 2016-08-11 09:18:35 |
| [363852](https://beta-pro.energytransitionmodel.com/scenarios/363852) | EE PL | 2016-08-11 09:18:35 |
| [423879](https://beta-pro.energytransitionmodel.com/scenarios/423879) | (voor)Beeld 80% CO2 reductie in 2050 in Nederland | 2016-08-11 09:21:27 |
| [423882](https://beta-pro.energytransitionmodel.com/scenarios/423882) | (voor)Beeld 95% CO2 reductie in 2050 in Nederland | 2016-08-11 09:21:27 |

**Comment by ChaelKruip** [comment] 2017-06-21 07:42
> The result is that beta is using the scenario instead of the preset. 

This feels like a fall-back option that we could remove right? I think it's a bit weird to open a database scenario when the preset fails (or is that not what happens).

**Comment by ChaelKruip** [comment] 2017-06-21 08:06
@antw @DorinevanderVlies does this affect the stability of the Urgenda scenario? Today is the launch of their booklet which refers to the scenario 😟

**Comment by antw** [comment] 2017-06-21 08:20
> This feels like a fall-back option that we could remove right? I think it's a bit weird to open a database scenario when the preset fails (or is that not what happens).

I was incorrect about this, it's not using the database scenario over the Preset. I'm still investigating why the two servers differ; I'll get back to you ASAP.

**Comment by DorinevanderVlies** [comment] 2017-06-21 08:47
To make things more confusing (or more clear): I also notice slight differences between the outcome of the scenario now and beginning of June (when I sent the outcomes to Urgenda).

I'm currently trying to recover the scenario settings of the 9th of June, but am pretty confident that the scenario itself didn't change since then (the only thing I can think of is a copy-paste mistake). 

![image](https://user-images.githubusercontent.com/19907658/27375250-ded44626-566e-11e7-849a-44fa3562a770.png)

**Comment by antw** [comment] 2017-06-21 09:29
> I also notice slight differences between the outcome of the scenario now and beginning of June (when I sent the outcomes to Urgenda).

We're you using beta for those "Dashboard" values? There was a fix to P2H after that date which might explain the difference.

I believe I'm closer to explaining why the two servers have different results: they're ordering household P2P and EV P2P differently when discharging:

Production:

```
  #<Merit::Flex::Base energy_flexibility_curtailment_electricity>
  #<Merit::Flex::Base energy_export_electricity>
  #<Merit::Flex::Storage households_flexibility_p2h_electricity>
  #<Merit::Flex::Base industry_flexibility_p2g_electricity>
  #<Merit::Flex::Base energy_flexibility_p2g_electricity>
  #<Merit::Flex::Storage transport_car_using_electricity>
  #<Merit::Flex::Storage households_flexibility_p2p_electricity>
```

Beta:

```
  #<Merit::Flex::Base energy_flexibility_curtailment_electricity>
  #<Merit::Flex::Base energy_export_electricity>
  #<Merit::Flex::Storage households_flexibility_p2p_electricity>
  #<Merit::Flex::Storage households_flexibility_p2h_electricity>
  #<Merit::Flex::Base industry_flexibility_p2g_electricity>
  #<Merit::Flex::Storage transport_car_using_electricity>
  #<Merit::Flex::Base energy_flexibility_p2g_electricity>
```

**Comment by DorinevanderVlies** [comment] 2017-06-21 11:03
> We're you using beta for those "Dashboard" values? There was a fix to P2H after that date which might explain the difference.

I was indeed using beta for those "Dashboard" values

The main difference is in energy import, export and curtailment and costs. So to me it seems plausible that flexibility (P2H) is the cause of the differences. Do you agree @antw?

**Comment by antw** [comment] 2017-06-21 11:08
I'm hopeful that this is now fixed, so I will close this issue. Please reopen if you find any other inconsistencies.

> So to me it seems plausible that flexibility (P2H) is the cause of the differences. Do you agree @antw?

I would imagine so; it's the only code change which happened after that date. The problem was that the P2H buffers were being emptied more than they should have; fixing that would likely have reduced the amount of energy imported since there is more heat available in the buffers.

**Closed by antw** 2017-06-21 11:08 UTC
Labels: Bug, Clean up
