### ISSUE TITLE
Using the cyclone furnace in steel industry should lower the CO2 emissions in NL start scenario

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3154] opened 2019-10-28 09:17 UTC
When in a 2050 NL start scenario the cyclone furnace  `industry_steel_hisarna_consumption_useable_heat_share` is set to 100 % it increase CO2 emissions, while they should be lower. 

The heat demand for the proces is in the graph created in the node energy_steel_hisarna_transformation_coal, it seems that this node creates an unnecessary overproduction. I cannot find why. 

![Screenshot 2019-10-28 at 10 16 23](https://user-images.githubusercontent.com/33415156/67666411-065c3080-f96c-11e9-9f6c-3fb65a3a44e8.png)
![Screenshot 2019-10-28 at 10 16 05](https://user-images.githubusercontent.com/33415156/67666413-06f4c700-f96c-11e9-973e-79ee8af9229c.png)

**Comment by michieldenhaan** [comment] 2019-10-28 09:47
Maybe the coupling carrier is broken? I don't know how this carrier is supposed to work but ``industry_steel_hisarna_consumption_useable_heat`` has ``input.coupling_carrier = 1.5256023862533`` but no actual energy coming in. Same goes for the blastfurnaces btw, in both present and future.

![beta-engine energytransitionmodel com - EnergyTransitionModel 2019-10-28 10-40-16(1)](https://user-images.githubusercontent.com/32056448/67668030-6e604600-f96f-11e9-8b67-dea550e9ca33.png)

**Comment by ChaelKruip** [comment] 2019-10-28 12:12
> Maybe the coupling carrier is broken? I don't know how this carrier is supposed to work but industry_steel_hisarna_consumption_useable_heat has input.coupling_carrier = 1.5256023862533 but no actual energy coming in. Same goes for the blastfurnaces btw, in both present and future.

The coupling carrier never actually carries energy (except during an initialisation phase which is something @antw knows more about) so that is expected behaviour.

**Comment by antw** [comment] 2019-10-28 13:18
> The coupling carrier never actually carries energy

This is correct. Coupling carrier is an old feature used to give hints to the graph during calculation, but both the slot and link shares and demands are set to zero after the calculation, as they aren't intended to carry energy.

**Comment by michieldenhaan** [comment] 2019-10-28 16:40
Interesting. Does anyone know what the logic behind these hints is? It looks like everything is working as intended, but energetically I understand it. Setting the blast furnace slider to 100% results in a node demand of 71 PJ for the``industry_steel_hisarna_consumption_useable_heat`` node.  At the same time the demand of the ``energy_steel_hisarna_transformation_coal`` node is set to 108 PJ, which is indeed 1.52 times 71 PJ (``input.coupling_carrier = 1.5256023862533``).

However, energetically speaking 65 PJ of this 71 PJ results in a ``steam_hot_water`` demand for the steel sector. At the same time 103 PJ of this 108 PJ results in a ``steam_hot_water`` supply. Hence, we end up with a 40 PJ production surplus. This 40 PJ is redistributed to other sectors, crowding out other heat sources, resulting in a CO2 increase.

Notifying @AlexanderWirtz

**Comment by ChaelKruip** [comment] 2020-12-14 13:46
@mabijkerk and @michieldenhaan can you make an assessment if this needs to be fixed?

**Comment by michieldenhaan** [comment] 2021-12-17 08:24
Fixed in recent steel update: https://github.com/quintel/etsource/pull/2576

**Closed by michieldenhaan** 2021-12-17 08:24 UTC
Labels: Pinned
