### ISSUE TITLE
Q: Can sub-sectors of the Industry sector be excluded from a scaled scenario?

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etmodel#1890] opened 2015-08-24 13:23 UTC
Sub-sectors:
- Metal
- Chemical
- Other

As @AlexanderWirtz would like to create a scaled scenario of the North of the Netherlands, that includes the chemical sector, but does _not_ include the metal subsector.

Including @ChaelKruip.

P.S. Extra complication: in the case of the metal sub sector: ideally, sometimes you may want to exclude steel, but not aluminium (i.e. a _sub sub_ sector).

P.S. An alternative but not equivalent: would it be possible to set a percentage per year slider to zero demand in the end year ? If that would be possible, it would at least for the end year be  possible to that manually from the interface.

**Comment by dennisschoenmakers** [comment] 2015-08-24 13:27
Consider this question low prio, compared to the work on etmoses for now.

**Comment by ChaelKruip** [comment] 2015-08-24 14:14
Duplicate of https://github.com/quintel/etmoses/issues/144?

**Comment by dennisschoenmakers** [comment] 2015-08-24 14:17
> Duplicate of quintel/etmoses#144?

Absolutely! Consider this another upvote :grinning:

**Comment by ChaelKruip** [comment] 2015-08-24 14:20
> would it be possible to set a percentage per year slider to zero demand in the end year

Those sliders reduce the demand in the sector by a factor (1.0 + slider_setting / 100)**N where 'N' is the number of years between the present and the future. This factor only goes to zero if slider_setting = -100 or if N goes to infinity (and -100 < slider_setting < 0). So, the only viable option with the current input statements would be to set the minimum slider setting to -100.

**Comment by dennisschoenmakers** [comment] 2015-08-24 14:24
> Those sliders reduce the demand in the sector by a factor (1.0 + slider_setting / 100)**N where 'N' is the number of years between the present and the future. This factor only goes to zero if slider_setting == -100 or if N goes to infinity (and -100 < slider_setting < 0). So, the only viable option with the current input statements would be to set the minimum slider setting to -100.

Reducing the minimum setting to -100 would be very unfortunate. I was looking for a 'trick' we could play, e.g. allow -100 in the text input for instance :smirk:

**Comment by ChaelKruip** [comment] 2015-08-24 14:37
> e.g. allow -100 in the text input for instance

Tricky stuff indeed! Would we allow -100 only or also all other values between -5 and -100?
This would be a 'feature' that only applies to a select number of sliders right?

**Comment by dennisschoenmakers** [comment] 2015-08-24 18:56
> Tricky stuff indeed! Would we allow -100 only or also all other values between -5 and -100?

I don't know, maybe an 'override' option: all though it's probably gonna mess up a lot: e.g. rendering the slider on a screen refresh, pressing the min/max button... :grin:

**Comment by michieldenhaan** [comment] 2020-11-13 10:46
Closing, scaling option has been removed.

**Closed by michieldenhaan** 2020-11-13 10:46 UTC
Labels: Features
