### ISSUE TITLE
It should be possible to have a dataset with 0 new or old household

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2300] opened 2016-11-14 11:05 UTC
Apparently, currently, the ETM crashes when this is the case, e.g. for Paddepoel.

**Comment by DorinevanderVlies** [comment] 2017-06-13 14:12
I cannot reproduce this

I tested this locally for the "Noorderplantsoen" dataset.
Setting either 0 old 0 new houses results in a working dataset

### Screenshots
**0 old houses, 2161 new houses**
![image](https://user-images.githubusercontent.com/19907658/27086562-dc26f882-5052-11e7-83b3-32b620456d00.png)
**2161 old houses, 0 new houses**
![image](https://user-images.githubusercontent.com/19907658/27086648-1a4da3fe-5053-11e7-8ad2-d1f785201103.png)
**0 old houses and 0 new houses**
![image](https://user-images.githubusercontent.com/19907658/27086352-3c7ea442-5052-11e7-85d9-20cda894f019.png)

**Comment by DorinevanderVlies** [comment] 2017-06-13 14:12
@dennisschoenmakers can we close this issue?

**Comment by DorinevanderVlies** [comment] 2017-06-14 08:17
Closing, please reopen if it occurs again

**Closed** 2017-06-14 08:17 UTC
Labels: Bug, Features
