### ISSUE TITLE
Primary use of biomass in industry should not be affected by CHP in agriculture

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#2942] opened 2019-02-04 15:36 UTC
The scenario with a lot of CHP's in agriculture (in Zuidplas) has a large primary demand of green gas in industry, while it is not used in industry. 

When the CHP's in Agriculture are closed, this green gas 'disappears'. You can find the scenario here:
https://pro.energytransitionmodel.com/scenarios/398487

With CHP's:
![screen shot 2019-02-04 at 16 31 37](https://user-images.githubusercontent.com/33415156/52218478-075ba800-289b-11e9-8b47-c2873a9ac18f.png)

Without CHP's:
![screen shot 2019-02-04 at 16 31 48](https://user-images.githubusercontent.com/33415156/52218479-075ba800-289b-11e9-8ea4-2a3073ccf05a.png)

**Comment by ChaelKruip** [comment] 2019-02-05 08:38
Could it be that excess heat from Agriculture CHPs is used (via the central heat network) in Industry? This would explain the increase of primary demand for biomass there...

**Comment by marliekeverweij** [comment] 2019-02-05 10:20
Very strange, but good catch!

The heat efficiency of the gas CHP in agriculture is 47% and the efficiency of the central gas back-up heater is 90%, so this could be the reason for a **decrease** of the green gas demand. But that is not the reason for the **disappearance** of the green gas demand.

I cannot reproduce the issue with the link you send me. Could you maybe show the chart "Demand and supply of the central heat network" in both cases?

**Comment by ChaelKruip** [comment] 2019-02-14 09:15
> I cannot reproduce the issue with the link you send me. Could you maybe show the chart "Demand and supply of the central heat network" in both cases?

@MartLubben what is the status here? Is this reproducible?

**Comment by MartLubben** [comment] 2019-02-14 10:11
@ChaelKruip Yes I can reproduce it. When Agriculture has a lot of heat surplus by CHP's on green network gas, while it uses a heat pump with TS itself, then the biomass demand of industry is 1.35 PJ. If the industry is heated by a back-up heater on network gas the demand is 0.21 PJ. This difference cannot be explained by the efficiencies only. 
![screen shot 2019-02-14 at 11 04 59](https://user-images.githubusercontent.com/33415156/52779826-39ae9780-3049-11e9-88e4-93d9834d9537.png)
![Uploading Screen Shot 2019-02-14 at 11.05.18.png…]()

**Comment by ChaelKruip** [comment] 2019-02-14 11:06
It turns out this is due to addition of dumped heat (excess of the heat network) to the industry category. This is confusing because the 'industry' category actually includes own use and losses of the 'energy' sector of the ETM. 

Perhaps we should change the label to say "industry and energy"?.

Closing this issue.

**Closed by ChaelKruip** 2019-02-14 11:06 UTC
