### ISSUE TITLE
Dashboard stays greyed out for some scenario's

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2356] opened 2017-03-10 12:21 UTC
I'm not sure, but it seems to happen after loading the flexibility chart:
![energietransitiemodel_-_je_eigen_onafhankelijke__volledige_en_op_feiten_gebaseerde_energiescenario_](https://cloud.githubusercontent.com/assets/1303760/23795193/81a2a162-0594-11e7-9968-2427e84df0a4.png)

**Comment by grdw** [comment] 2017-03-10 12:30
How do you *exactly* reproduce this?

I loaded it just fine by adding the chart, locking it and adding a ton of windmills.

**Comment by grdw** [comment] 2017-03-10 13:10
I have no idea how this is caused. It almost looks as though the cart already starts 'updating' before the first ajax request is finished from ETEngine (which causes the values to be blank).

**Comment by antw** [comment] 2017-03-10 13:27
> I'm not sure, but it seems to happen after loading the flexibility chart:

Do you have a scenario ID? It would also be useful to have the "Network" tab open when this happens again, since that will give away if the ETEngine request failed (it will appear in red), or if this is something in the ETM front-end.

> It almost looks as though the cart already starts 'updating' before the first ajax request is finished from ETEngine (which causes the values to be blank).

We're you able to reproduce it? If so, how? 😆

**Comment by grdw** [comment] 2017-03-10 14:02
> We're you able to reproduce it? If so, how?

@ChaelKruip showed me. Appearantly if you load the flexibility chart and than *refresh* the page, the chart fails. I was only able to reproduce it with the ["100% duurzaam"](https://beta-pro.energytransitionmodel.com/scenarios/155680) scenario.

**Comment by ChaelKruip** [comment] 2017-03-21 09:01
Any luck reproducing this @antw?

**Comment by antw** [comment] 2017-03-21 19:20
> Any luck reproducing this @antw?

Yes. The ETM front-end seems to be sending multiple requests to ETEngine to fetch chart data; it should not be doing this. I'll look into it in more depth shortly.

**Comment by antw** [comment] 2017-03-27 14:26
I'm fairly optimistic this has been resolved by cc4dc0b and c4fcd1e on the report-liquid branch. I will leave this open for now; it will close automatically when that branch is merged with master.

**Closed** 2017-04-06 16:20 UTC
Labels: Bug
