### ISSUE TITLE
Electricity production of operational CHP should not be zero

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#2317] opened 2016-12-22 12:56 UTC
![energytransitionmodel](https://cloud.githubusercontent.com/assets/1303760/21426286/5b44bd08-c84e-11e6-8b9b-5eefc083093b.png)

As observed in [this scenario]()https://pro.energytransitionmodel.com/scenarios/308870

**Comment by antw** [comment] 2016-12-22 14:12
I think this is a duplicate of #2314. It's an agriculture CHP and should be disabled by the scaling settings. Here's what the same scenario looks like locally (and on beta):

![screen shot 2016-12-22 at 14 10 43](https://cloud.githubusercontent.com/assets/4383/21428174/a0cfc636-c850-11e6-9c8e-571c2aed4909.png)

**Closed by antw** 2016-12-22 14:12 UTC
Labels: Bug, Priority
