### ISSUE TITLE
Visualisation error in hourly_stacked_area chart

### ISSUE THREAD

**Issue by mabijkerk** [quintel/etmodel#3863] opened 2021-11-22 15:36 UTC
Some curves show minor errors in the visualisation when they go to 0 on the new `hourly_stacked_area` charts. It mainly seems to occur for battery curves.

Example on the `price-sensitive-flex` branch:
![image](https://user-images.githubusercontent.com/67338510/142889721-c3bd421a-a042-47a0-a289-c0a9d7451c7f.png)

Example on the `innovations-flex` branch:
![image](https://user-images.githubusercontent.com/67338510/142889816-90dc2752-59e6-4f51-9ce6-3f1aedd336c5.png)

**Comment by antw** [comment] 2021-11-22 16:46
I knew I'd seen this problem before. It was fixed on the price-sensitive-flex branch, but the change wasn't incorporated into the innovations-flex branch. 🤦 

@mabijkerk Your screenshot from the price-sensitive-flex branch shows the problem is present there, but I'm not able to reproduce it myself. The lack of a translation for the chart title and battery charging and discharging being the same colour makes me wonder if this is an old screenshot? It looks similar to the II3050 regional governance scenario which, for me, doesn't have this problem:

![Flexible electricity demand and supply per hour 1495010](https://user-images.githubusercontent.com/4383/142901111-41157ae6-5de3-4551-aaa5-aa9f741b3b04.png)

**Comment by mabijkerk** [comment] 2021-11-22 17:04
> It was fixed on the price-sensitive-flex branch

My mistake, I thought it was still open there. The chart shown above for the `price-sensitive-flex` branch is indeed an old screenshot.

When I run the scenario now (II3050 National governance), the series do stack nicely:
<img width="500" alt="Screenshot 2021-11-22 at 18 03 54" src="https://user-images.githubusercontent.com/67338510/142903928-08b6b30c-51a9-4525-a919-96d96d3c2e68.png">

**Closed** 2021-11-22 17:45 UTC
Labels: Charts, effort:1
