### ISSUE TITLE
dynamic response chart does not load correctly

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2491] opened 2017-09-21 12:30 UTC
This is troublesome as the scenario freezes. The user can set sliders, but they are not saved.

Usually refreshing the browser works. However, not all users are aware of the fact that the scenario has frozen. 

Notifying @grdw and @ChaelKruip

**Comment by grdw** [comment] 2017-09-22 10:14
![screen shot 2017-09-22 at 12 13 07](https://user-images.githubusercontent.com/2676542/30739957-73d76a6e-9f8f-11e7-93aa-79572da1d89e.png)

Might be related. But I was testing with my local ETModel (with the beta engine instead of the local one) and came across this bug. Do you think it might be related @DorinevanderVlies ?

**Comment by grdw** [comment] 2017-09-22 13:18
Ok, ignore my previous comment. I see what is happening.

![screen shot 2017-09-22 at 15 17 13](https://user-images.githubusercontent.com/2676542/30746192-30aa9436-9fa9-11e7-81db-b3700b86add5.png)

If you click faster than the page can load, so 'Flexibility' -> 'Open pane' -> 'Slide the heat slider', all things freeze. I get it 👍 That's why refreshing your browser fixes the problem.

**Comment by DorinevanderVlies** [comment] 2017-09-22 13:29
> If you click faster than the page can load

Is the the cause of the problem that the dynamic heat chart takes a long time to load? Or something else?

**Comment by grdw** [comment] 2017-09-22 13:33
Very well could be. I'm still investigating 🔍 . The problem is that the data that belongs to the chart isn't present the moment that it tries to show the chart.... which is something that changed some time ago. I need to check some stuff 😄 one moment.

**Comment by grdw** [comment] 2017-09-22 14:20
To reproduce this very quickly:

![clickclickclick](http://g.recordit.co/B4dFc6qJ8D.gif)

**Comment by grdw** [comment] 2017-09-22 14:22
I have no clue why this is happening exactly as is. And why specifically for 'yearly load charts'. It's a bit frustrating. The only thing I can think of is the code at [here](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/models/chart_list.coffee) is a little dodgy, but I wouldn't be able to put my finger on it.

Maybe @antw knows, stating that he edited it the last time.

**Comment by antw** [comment] 2017-09-26 15:05
I think this has been an occasional problem since the time-series charts were first introduced. I think that `draw` [is trying to access the data for the chart](https://github.com/quintel/etmodel/blob/1f4c0af949667c388a72e0454f2609d1208615bd/app/assets/javascripts/lib/views/d3_yearly_chart_view.coffee#L15) (via `dataForChart`) when there is no guarantee that data has been fetched from ETEngine yet. IIRC data is not meant to be accessed until `refresh` is called.

It also happens in the excess events chart [which maps over the data before it is available](https://github.com/quintel/etmodel/blob/1f4c0af949667c388a72e0454f2609d1208615bd/app/assets/javascripts/d3/merit_order_excess_events.coffee#L58).

**Comment by ChaelKruip** [comment] 2017-09-28 09:31
> when there is no guarantee that data has been fetched from ETEngine yet

Is there a way to 'block' executing the drawing of the chart until the data has arrived?

**Comment by marliekeverweij** [comment] 2019-08-19 15:20
I cannot reproduce this issue, so I am closing it :)

**Closed by marliekeverweij** 2019-08-19 15:20 UTC
Labels: Bug
