### ISSUE TITLE
User should also be able to analyze energy use per function

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2264] opened 2016-09-28 17:37 UTC
Akin to the Energy Rapport:
* power and lighting
* transport and mobility
* low temperature in heating our houses and buildings
* high temperature in industry

**Comment by ChaelKruip** [comment] 2016-09-29 09:34
Closing as this is a duplicate of https://github.com/quintel/etmodel/issues/1986

**Closed by ChaelKruip** 2016-09-29 09:34 UTC
Labels: features, Question
