### ISSUE TITLE
On beta excess electricity usage is lower than the total excess electricity 

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2478] opened 2017-09-08 10:05 UTC
Electricity Conservation fails.
On beta excess electricity usage differs is lower than the total excess electricity.

In a scenario with 10.000 inland windturbines the total excess electricity is 41.56 PJ, the total excess electricity storage sum is 39.612 PJ. On live these numbers are the same: 40.1 PJ.

In a scenario without flexibility options the total excess electricity storage sum consists of curtailment and export.

**Beta:**
[turk_excess_electricity_storage_sum](https://beta-engine.energytransitionmodel.com/data/722702/gqueries/turk_excess_electricity_storage_sum) = 39.61 PJ
[electricity_exported](https://beta-engine.energytransitionmodel.com/data/722702/gqueries/electricity_exported) = 29.00 PJ
[electricity_curtailed](https://beta-engine.energytransitionmodel.com/data/722702/gqueries/electricity_curtailed) = 10.61 PJ

[turk_excess_electricity_from_production.value](https://beta-engine.energytransitionmodel.com/data/722702/gqueries/turk_excess_electricity_from_production.value) = 41.59 PJ

**Live:**
[turk_excess_electricity_storage_sum](https://engine.energytransitionmodel.com/data/335605/gqueries/turk_excess_electricity_storage_sum) = 40.11 PJ
[electricity_exported](https://engine.energytransitionmodel.com/data/335605/gqueries/electricity_exported) = 29.170 PJ
[electricity_curtailed](https://engine.energytransitionmodel.com/data/335605/gqueries/electricity_curtailed) = 10.94 PJ

[turk_excess_electricity_from_production.value](https://engine.energytransitionmodel.com/data/335605/gqueries/turk_excess_electricity_from_production.value) = 40.11 PJ

**Background**
This issue originates from a failure on Mechanical Turk:
rpec ./spec/flexibility/flexibility_spec.rb:185 # Flexibility Electricity Conservation Electricity should be conserved between excess production and storage

notifying @ChaelKruip

**Comment by antw** [comment] 2017-09-08 18:27
This happens even in a blank scenario.

It appears to be caused by the heat pumps; if you set the scenario to 100% combi-boilers the difference between the two queries is zero.

**Comment by antw** [comment] 2017-09-08 19:03
Seems to happen with resistive electric heaters as well, which implies some interaction between Merit and Fever may be to blame. I'm not sure how or why though, because the demands set on the graph are identical between production and beta.

100% resistive water heaters:

Demand on production: 69.28B
Demand on beta: 69.28B

It could be something to do with the `turk_excess_electricity_from_production` query; even [in the above scenario on production](https://engine.energytransitionmodel.com/data/335630/gqueries/turk_excess_electricity_from_production) it implies there's a deficit:

![screen shot 2017-09-08 at 20 00 46](https://user-images.githubusercontent.com/4383/30227141-78be66dc-94d0-11e7-94e5-3a8463f3271c.png)

**Comment by ChaelKruip** [comment] 2017-09-08 19:40
Just a wild guess from the cigar lounge: losses of the HV network?

**Comment by ChaelKruip** [comment] 2017-09-19 14:35
The difference in the present year are expected and completely due to imported electricity which is not counted as 'production'.

The difference in the future year disappears (almost) completely when heating all houses with gas:
![cursor_and_energytransitionmodel](https://user-images.githubusercontent.com/1303760/30597584-afd0bc6c-9d57-11e7-9cb7-2a7895af447c.png)

This suggests that there might be some effect where more electricity is used in heating/hot water than is accounted for by the production query.

Providing all space heating with `households_space_heater_electricity', gives a difference of a whopping 195 PJ!
![cursor_and_energytransitionmodel](https://user-images.githubusercontent.com/1303760/30597811-62293a06-9d58-11e7-8b47-6525d09dac14.png)

**Comment by ChaelKruip** [comment] 2017-09-19 14:45
Taking into account both 'import' and the 'shortage node', the differences are reduced to numerical noise:
![cursor_and_energytransitionmodel](https://user-images.githubusercontent.com/1303760/30598443-01d4aba2-9d5a-11e7-958c-3e27915d7edf.png)

**Comment by ChaelKruip** [comment] 2017-09-19 14:47
I propose to use the following query for the mechanical turk test:
```
DIVIDE(Q(total_electricity_produced), BILLIONS) + 
V(energy_import_electricity, "demand/BILLIONS")+
V(energy_power_hv_network_shortage, "demand/BILLIONS") - Q(demand_in_source_of_electricity_production)
```

@DorinevanderVlies does this solve your issue or is there other electricity unaccounted for in your opinion?

**Comment by DorinevanderVlies** [comment] 2017-09-19 14:49
I think this 195 PJ is not the issue. It just means that with the current production park 195 PJ is imported when heating all houses with electric heaters. I think that is realistic.

To clarify the issue a bit more:
The excess electricity calculated by looking at the difference between production and demand (https://github.com/quintel/etsource/blob/master/gqueries/mechanical_turk/flexibility/turk_excess_electricity_from_production.gql) should equal the electricity that is used by flexibility technologies, curtailment and export (https://github.com/quintel/etsource/blob/master/gqueries/mechanical_turk/flexibility/turk_excess_electricity_storage_sum.gql). 
 
Either these gqueries (or the groups they refer to) are incomplete or some excess electricity is "lost".

**Comment by DorinevanderVlies** [comment] 2017-09-20 18:25
Reopening as the implemented gquery acts slightly different as the gquery proposed in this issue.

For a scenario with 10,000 inland wind turbines and 20% hydrogen cars

```
DIVIDE(Q(total_electricity_produced), BILLIONS) + 
V(energy_import_electricity, "demand/BILLIONS")+
V(energy_power_hv_network_shortage, "demand/BILLIONS") - Q(demand_in_source_of_electricity_production)
```
gives 40.03740447912173  PJ which is the same as the storage gquery

```
    DIVIDE(Q(total_electricity_produced), BILLIONS) + 
    DIVIDE(Q(energy_import_electricity), BILLIONS) + 
    DIVIDE(Q(energy_power_hv_network_shortage), BILLIONS) +     
    - Q(demand_in_source_of_electricity_production)
```
gives 39.80154676303226 PJ which is slightly different.

I'll look into this tomorrow

**Comment by ChaelKruip** [comment] 2017-09-21 07:59
Fixed with https://github.com/quintel/etsource/pull/1353

**Closed** 2017-09-21 08:02 UTC
Labels: Bug
