### ISSUE TITLE
Merit Order chart should also contain geothermal (electricity)

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2131] opened 2016-05-24 14:03 UTC
![image](https://cloud.githubusercontent.com/assets/104830/15506738/058f4986-21c9-11e6-9f54-3e7220a25ab5.png)

**Comment by jorisberkhout** [comment] 2016-05-24 14:08
Duplicate of https://github.com/quintel/etmodel/issues/2102. Closing this one as the other one contains some more information.

**Closed by jorisberkhout** 2016-05-24 14:08 UTC
Labels: Bug
