### ISSUE TITLE
CO2: what is the status?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1932] opened 2015-10-01 07:19 UTC
Discussion with @jorisberkhout made me realise that the possible reasons for the CO2 discrepancy as observed between beta and live can be due to several things:

* The (confirmed) omission of the coal gas export node
* The possible omission of co2 attributes for carriers
* The omission of some own use due to the improper modeling of the refinery sector
* ...

@AlexanderWirtz has looked into the differences between the CO2 emissions quoted by the ETM and those of the UNFCCC (see https://github.com/quintel/etdataset/issues/609). 

@AlexanderWirtz could you log in this issue the current status of your findings before we all forget the details?

**Comment by jorisberkhout** [comment] 2015-11-20 12:33
Let's resolve this before the February deploy.

**Comment by AlexanderWirtz** [comment] 2016-01-12 10:57
1. We use slightly different CO2 emission characteristics for our carriers. the NL dataset, for example, specifies FCE attributes for different type of coal from different parts of the world. This means the mix of origins set for the dataset and perhaps later chosen by a user actually determines the CO2 emissions per GJ of coal. The UNFCCC on the other hand, uses uniform numbers for all carriers. This explains about half the difference, as far as I can remember
2. We have some `coal_gas` export for the Dutch dataset, which is caused by our inability to burn this in the steel sector CHP's in IJmuiden. We cannot do so, because these CHPs do not live in the steel sector, but are main activity CHPs and connecting the coal_gas production from the steel sector to these is too complicated (I forget the details, but [this issue](https://github.com/quintel/etdataset/issues/225) explains a lot). The error as a result of this bug varies each year, as the cokes demand and production and concomitant coal_gas production varies. 
3. Own use of energy in the refineries / energy industry is not entirely correctly modeled despite numerous attempts at improving this. The contribution to the delta with UNFCCC varies for each year and each energy balance.

**Comment by AlexanderWirtz** [comment] 2016-01-12 10:57
@jorisberkhout what needs to be done to close this?

**Comment by AlexanderWirtz** [comment] 2016-01-12 10:58
also see: https://github.com/quintel/etdataset/issues/609

**Comment by jorisberkhout** [comment] 2016-01-19 14:15
@AlexanderWirtz , what did we decide to do with this issue in the end?

**Comment by AlexanderWirtz** [comment] 2016-01-20 08:20
This issue exists for reference sake. Not actionable now that 2013 dataset for Amal will be deployed.

**Closed** 2016-01-20 08:20 UTC
Labels: Priority, Question
