### ISSUE TITLE
P2H Heat Pump for district heating should not produce MUCH more heat than P2H electric boiler for same installed capacity

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3335] opened 2020-04-30 10:17 UTC
In [this scenario](https://pro.energytransitionmodel.com/saved_scenarios/9171) the P2H heat pump displays weird behaviour. When installing equal (heat output) capacities of the P2H HP and the P2H boiler for district heating, the former produces much more heat at impossibly high full load hours.

Situation with P2H boiler @750 MW:
![image](https://user-images.githubusercontent.com/1303760/80698948-7f833e80-8adb-11ea-9181-3800eca7831c.png)
producing 13.21 PJ with 4892 FLH.

Situation with P2H HP @750 MW:
![image](https://user-images.githubusercontent.com/1303760/80699212-e43e9900-8adb-11ea-8a0d-fd4c5207c8df.png)
Producing 58.88 PJ at 21806 FLH (!). The maximum FLH is 8760 as this is the number of hours in the year so, something non-physical is going on here!

Because the PH2 HP has a COP of 4.5 and 13.21 PJ * 4.5 ~ 59 PJ, I suspect that the installed capacities of these technologies refer to the electricity **input** capacity rather than the heat **output** capacity as should be the case.

Perhaps fallout from https://github.com/quintel/etmodel/issues/3324?

Including @AlexanderWirtz @michieldenhaan @marliekeverweij

**Comment by antw** [comment] 2020-04-30 11:04
Are you sure you linked the correct scenario? I can't reproduce the results you're showing in those screenshots.

With 750MW of boiler capacity, the boiler produces 1.2PJ of heat, while the heat pump produces 5.36PJ. *Those* numbers look correct to me: the heat pump uses 22.22% electricity to produce heat; the rest is made up from ambient heat.

What I cannot reproduce in a copy of that scenario is the *amount* of energy and the resulting FLH.

**Comment by AlexanderWirtz** [comment] 2020-04-30 11:42
> What I cannot reproduce in a copy of that scenario is the amount of energy and the resulting FLH.

@antw I think the link is correct, but be careful that you need to place these P2H units higher in the Flex merit order (typically before P2G), before they get used much. That may be why you cannot reproduce the FLH.

> Edit: Oh I see; the sliders set heat output capacity, so that's why you expect to see the same output. I will investigate.

Yes, the issue is indeed that we are setting output capacity and therefore expect them to make pretty much the same amount of heat. 
In a nutshell: X MW installed output capacity of the P2H heat pump should use less power to make the same amount of heat as X MW installed output capacity of P2H electric boiler

**Comment by antw** [comment] 2020-04-30 12:15
I've pushed [a fix](https://github.com/quintel/etengine/commit/87d6c7271d43923516a7005dd8574027f8c0a944) to production. It turns out that these are the only two technologies not to have a `merit_order.subtype` value, which means that ETEngine falls back to its base class for flex technologies. This class doesn't compensate for input/output efficiency.

Production now has a quick fix in place, but I have not fixed beta: I want to come up with something more robust.

> but be careful that you need to place these P2H units higher in the Flex merit order (typically before P2G), before they get used much.

I think we need to revisit the decision to hide flex options with no capacity, but that's a discussion which I'll take elsewhere.

**Comment by AlexanderWirtz** [comment] 2020-05-01 09:01
Thanks @antw for the quick fix.

**Comment by marliekeverweij** [comment] 2020-05-25 09:25
@antw I am wondering: has this issue been fixed in this PR https://github.com/quintel/etengine/pull/1113?

**Comment by antw** [comment] 2020-05-26 10:04
This has indeed been fixed.

**Closed** 2020-05-26 10:20 UTC
Labels: Bug
