### ISSUE TITLE
The rounding in the documentation Excel tool-tip download is not going well for all household heating technologies

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#3241] opened 2020-02-28 09:13 UTC
The capacity of the following technologies is shown 0.0 MW
- combi boiler in HH
- wood pellet stove in HH
- Gas-fired heater in HH
- Gas-fired heater in BD

In all other heating technologies it is going well. Scaling to kW would be a nice to have

![Screenshot 2020-02-28 at 10 00 04](https://user-images.githubusercontent.com/33415156/75525973-292d4d00-5a11-11ea-8d5b-efd3cce2b75d.png)
![Screenshot 2020-02-28 at 09 59 54](https://user-images.githubusercontent.com/33415156/75525978-2af71080-5a11-11ea-84cf-3e482d954eb5.png)

**Comment by marliekeverweij** [comment] 2020-02-28 09:17
Same issue as https://github.com/quintel/etmodel/issues/3233 ;)

**Comment by noracato** [comment] 2020-02-28 09:38
Closing this issue because it's a duplicate of #3233

**Closed by noracato** 2020-02-28 09:38 UTC
