### ISSUE TITLE
If the merit order is off, the load curves should not be downloadable

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#1997] opened 2016-01-27 11:13 UTC
I don't understand that they show information at all :confused:

**Comment by antw** [comment] 2016-01-27 11:26
> I don't understand that they show information at all

The merit order still runs in a very limited fashion when it is disabled; it needs to do so for the LOLE calculation.

**Comment by jorisberkhout** [comment] 2016-01-29 12:48
Assigning @grdw to get the buttons hidden when the MO is switched off.

These buttons that is!

<img width="465" alt="screen shot 2016-01-29 at 13 46 50" src="https://cloud.githubusercontent.com/assets/4669028/12675995/d5889160-c68e-11e5-87dd-ee89f08b3a43.png">

**Comment by grdw** [comment] 2016-02-01 13:37
Turned off:
![screen shot 2016-02-01 at 2 36 43 pm](https://cloud.githubusercontent.com/assets/2676542/12718820/488bdd02-c8f1-11e5-9d5a-a2edc64c7f4a.png)

Turned on:
![screen shot 2016-02-01 at 2 36 52 pm](https://cloud.githubusercontent.com/assets/2676542/12718819/488a441a-c8f1-11e5-9f34-6f2460ce35e2.png)

**Comment by jorisberkhout** [comment] 2016-02-08 16:35
Re-opening this as I don't see the download buttons anymore, even when the merit order switched on. @grdw, any ideas?

**Comment by grdw** [comment] 2016-02-09 08:12
> any ideas?

In all my honesty: not really. It's fine with me on `beta.pro`. Did you do anything special prior to toggling the merit order?

**Comment by jorisberkhout** [comment] 2016-02-09 09:01
I cannot reproduce it either. Closing.

**Closed by jorisberkhout** 2016-02-09 09:01 UTC
Labels: clean up, features
