### ISSUE TITLE
ETModel requires base_value from ETEngine scenario scaling

### ISSUE THREAD

**Issue by dennisquintel** [quintel/etmodel#2383] opened 2017-04-25 11:48 UTC
Reproduce:
1. Go to energytransitiemodel.com
2. Load the SER 2023 scenario (preset)
3. Click on 'scale this scenario'
4. Enter 400.000
5. "Are you sure?" -> OK
6. 500 Error! :(

![image](https://cloud.githubusercontent.com/assets/104830/25383702/84a2f932-29bd-11e7-923f-e2bea66a4748.png)

**Comment by grdw** [comment] 2017-04-25 12:01
![screen shot 2017-04-25 at 13 56 16](https://cloud.githubusercontent.com/assets/2676542/25384146/79b1265a-29bf-11e7-89c8-efd66669c916.png)

```ruby
    default   = Current.setting.scaling[:base_value]

    percent   = (value.to_f / default) * 100

    precision = (percent > 10 ? 0 : (percent < 1 ? 2 : 1))
```

By debugging my guess is that is has something to do with the latest commit: https://github.com/quintel/etmodel/commit/4a5d46727c81fef8302117a6765a2a4dd51fc387 Stating that `default` is `nil`. 🤔

**Comment by antw** [comment] 2017-04-25 12:03
I've pushed a (hot)-fix out already. `base_value` seems to be available when you *already* have a scaled scenario, but not if you start a new one... :confused:

**Comment by dennisschoenmakers** [comment] 2017-04-25 12:03
> I've pushed a (hot)-fix out already. base_value seems to be available when you already have a scaled scenario, but not if you start a new one... 😕

Great, can we deploy to staging *and* production? :)

**Comment by antw** [comment] 2017-04-25 12:04
> Great, can we deploy to staging and production? :)

Already done.

**Comment by grdw** [comment] 2017-04-25 12:05
The nice fix is probably to add `base_value` to [these lines](https://github.com/quintel/etmodel/blob/master/app/models/api/scenario.rb#L76-L80) or?

**Comment by antw** [comment] 2017-04-25 13:09
> The nice fix is probably to add `base_value` to these lines or?

Isn't that method used only to translate values from the scaling form into attributes to send to ETEngine? The scaling form does not have a `base_value` attribute (it is computed by ETEngine when the scenario is created).

What I've learned is:

* If you load an already-scaled scenario (e.g. /scenarios/665945 → Load) the `base_value` is set ([because it comes from ETEngine](https://github.com/quintel/etmodel/blob/062c485d5b0a735360a5b770a53789b4e0d16579/app/models/setting.rb#L65)).
* If you create a new scaled scenario using the scaling form, the `base_value` is set by `load_from_scenario`, but is then overwritten (removed) by [a call to `assign_scaling_attributes`](https://github.com/quintel/etmodel/blob/062c485d5b0a735360a5b770a53789b4e0d16579/app/controllers/scenarios_controller.rb#L110) as [the form params](https://github.com/quintel/etmodel/blob/062c485d5b0a735360a5b770a53789b4e0d16579/app/controllers/application_controller.rb#L95-L97) are still present.

I feel like `ApplicationController#assign_scaling_attributes` should be merged with `Setting#load_from_scenario`, and the scaling settings should come from ETEngine and not the form. Sadly I think this is easier said than done because of the myriad of different ways ETModel starts and loads scenarios.

**Comment by antw** [comment] 2017-04-25 14:02
I've changed the title to describe the intent of the offending commit. @jorisberkhout noticed earlier today (with input from a client) that the scaling summary in the settings menu showed a value which was different from that observed in the graph.

The settings menu said the scaled scenario was 0.94% of the original size, when in fact the graph was scaled to 0.82%. This is because the settings menu was using the default area number_of_residences (~7.4M households) instead of the custom scenario value – the so-called `base_value` – of 8.5M. 4a5d467 was intended to fix that.

It would be nice to revisit this when we have the time. *(@jorisberkhout please jump in here if you feel this is urgent for the client in question).*

**Comment by jorisberkhout** [comment] 2017-04-25 14:21
> (@jorisberkhout please jump in here if you feel this is urgent for the client in question).

Not urgent at all! Thanks.

**Comment by michieldenhaan** [comment] 2020-11-13 10:46
Closing, scaling option has been removed.

**Closed by michieldenhaan** 2020-11-13 10:46 UTC
