### ISSUE TITLE
Saved scenario 8963 does not load properly 

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3333] opened 2020-04-29 12:40 UTC
[This saved scenario](https://pro.energytransitionmodel.com/saved_scenarios/8963) does not load properly.
As far as I found it corresponds to 748720, which is a protected scenario. 

My guess is that something went wrong with a migration, but I haven't been able to figure it out.

notifying @noracato

**Comment by antw** [comment] 2020-04-29 12:49
The scenario region is `RGGL04_noord_veluwe`, which was removed in quintel/etsource@90ccf1cd2.

**Comment by michieldenhaan** [comment] 2020-04-29 14:02
It does seem to work again now?

I wrote a migration to prevent this from happening (see https://github.com/quintel/etengine/blob/master/db/migrate/20200417150435_rename_some_old_datasets.rb). But both the ETSource commit and ETEngine migration shouldn't be on PRO yet. Maybe it was cherry-picked by accident?

**Comment by michieldenhaan** [comment] 2020-04-29 14:11
> Maybe it was cherry-picked by accident?

No that's not the case as `RGGL04_noord_veluwe` is still available on PRO.
I think this was caused by commit quintel/etsource@3bbe4ec610 being imported in the PRO engine for a short while instead of quintel/etsource@8e5729ab7eb176fcff6ab6470251d543b84392e6, causing the PRO engine to run on the ETSource master tree. This also broke the new storage capacity slider.

I've imported the latest production commit now, closing.

**Closed by michieldenhaan** 2020-04-29 14:11 UTC
Labels: Bug
