### ISSUE TITLE
Dashboard stays 'washed out'.

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etmodel#2238] opened 2016-09-13 11:51 UTC
I pulled many sliders in 576931 on beta.

![image](https://cloud.githubusercontent.com/assets/104830/18472668/0cc8932c-79b9-11e6-9a0a-caaaac706eb9.png)

Re-assign at will @jorisberkhout

**Comment by jorisberkhout** [comment] 2016-09-13 12:42
When I opened your scenario, I worked as expected (i.e. all dashboard values were calculated and shown). However when I pulled some more sliders, the dashboard was 'washed out' for a few seconds but did re-appear after some time. In the time that it was frozen, I caught this very generic error:

<img width="1072" alt="screen shot 2016-09-13 at 14 35 57" src="https://cloud.githubusercontent.com/assets/4669028/18473958/d75808a6-79bf-11e6-9ca0-0e6dc10752be.png">

I am guessing that this is a very generic error, but would love to hear if @antw or @grdw can tell me a little more. It seems to do with `activesupport-4.1.5`, which reminded me of https://github.com/quintel/atlas/commit/ce45457.

**Comment by antw** [comment] 2016-09-13 12:48
> I am guessing that this is a very generic error

It means something is recursing infinitely. The version of Ruby on our servers is too old to give any more useful information when this happens, which is why ActiveSupport gets the blame. I'll look into it.

**Comment by jorisberkhout** [comment] 2016-09-13 13:13
Thanks!

**Comment by antw** [comment] 2016-09-13 13:28
I can't reproduce this. Do you remember which sliders you moved and which chart(s) were open?

**Comment by jorisberkhout** [comment] 2016-09-13 13:35
> Do you remember which sliders you moved and which chart(s) were open?

Unfortunately not. I will try again and report here what you need to do to reproduce this.

**Comment by grdw** [comment] 2016-09-14 08:37
I'm currently trying to reproduce this aswell. I'm dragging all the sliders from top to bottom. What clearly doesn't trigger it:

- Clicking on any slider randomly a lot (it just queues all the requests quiet nicely and nothing odd happens)
- Dragging multiple sliders randomly doesn't trigger anything for me.

Dragging multiple sliders over a slower connection does however cause the 'washed out' interface to stay for a while. The numbers will change in the 'washed out' stage and after the final request is done it will come back to normal. Like this:

<img src="http://g.recordit.co/zc3a3QL3oY.gif"/>

I do however never see the 500 error as described by @jorisberkhout [here](https://github.com/quintel/etmodel/issues/2238#issuecomment-246668745) 😩 and I'm not even sure it's related to this problem.

Either we know which specific combination of sliders causes the error

**Comment by jorisberkhout** [comment] 2016-09-14 08:52
Thanks, @grdw . If it's just a delay, I would say that this is not deploy critical, so removing it from the milestone. I will leave this issue open though.

**Comment by marliekeverweij** [comment] 2019-08-19 15:28
As this issue is really hard to reproduce and hasn't occurred in the past 1,5 year, I think we can close this issue :)

**Closed by marliekeverweij** 2019-08-19 15:28 UTC
Labels: Bug, Layout
