### ISSUE TITLE
P2H industry: demand curves of hydrogen / network gas do not respond to P2H

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#3605] opened 2021-02-05 13:18 UTC
I am a bit confused by the hourly export of hydrogen demand in the II3050 scenario nationale sturing.

The chemicals sector has hydrogen burners and P2H. 
As I understand at times of excess electricity P2H burners should take over from the hydrogen burners. This seems to happen.
The export of electricity demand shows non-zero electricity demand for `industry_chemicals_other_flexibility_p2h_network_gas_electricity.input`

However, hydrogen demand for `industry_chemicals_refineries_burner_hydrogen.input` shows a flat curve

I would expect the hydrogen demand to be lower when the P2H burners are on. Curious how this can be explained and where I can find the correct hydrogen curve for chemicals.

Assigning @marliekeverweij as in my head you are queen flex. Please reassign if appropriate.

![image](https://user-images.githubusercontent.com/19907658/107038132-5efbb980-67bc-11eb-84eb-5d6301c3b119.png)

![image](https://user-images.githubusercontent.com/19907658/107038191-733fb680-67bc-11eb-826a-a362a465f084.png)

**Comment by marliekeverweij** [comment] 2021-02-05 13:44
Good catch! This is not the intended behaviour of P2H.

During the 'modify profiles'-project the names of the profiles used in the P2H nodes have changed, could this have caused this issue @antw ?

https://github.com/quintel/etsource/commit/16eb4f3d2d7fe4f1e1bd51950250bfc8ec4794ba
https://github.com/quintel/etsource/commit/738356ab248172a4d01bd4828614b8d4f7934ace

**Comment by marliekeverweij** [comment] 2021-02-05 13:57
And the profiles in the P2H subordinate and leader nodes now use the same profile. For example the profile `industry_chemicals_heat` is used in both `industry_chemicals_other_flexibility_p2h_hydrogen_electricity` and `industry_chemicals_other_burner_hydrogen`. Could this play a role?

**Comment by antw** [comment] 2021-02-05 14:09
> industry_chemicals_heat

As far as I'm aware, these are just copies of the flat profile.

**Comment by marliekeverweij** [comment] 2021-02-05 15:30
> As far as I'm aware, the new curves are just copies of the flat profile.

Yes, that's true. Could it be that the same profile name triggers an error? 

It could also be that something else causes this issue, but I cannot think of what!

**Comment by antw** [comment] 2021-02-05 15:33
A fix is on its way to beta.

We need to fetch the demand of the P2H node before and after Merit runs in order to determine if it changed. If it did, the H2 calculation knows it needs to adjust the curve for the burner. This was happening too late: the "before merit" P2H value was being fetched when Merit had *already* run.

I believe the result was that the energy from P2H was being averaged across the whole year – causing the burner demand to 
fall, but stay flat.

I have moved the initialisation of H2 to happen *before* Merit and this seems to have fixed the issue. I was concerned my fix might cause a recurrence of #3354, but this does not appear to be the case; the network gas import and curve both remain consistent.

@DorinevanderVlies I'm going to assign this issue back to you: would you mind checking that the fix has the desired effect? If so, this can be closed and I'll push the change to production.

---

```ruby
V(industry_chemicals_other_burner_hydrogen, hydrogen_input_curve).rotate(48).take(24)
```

| Production | Beta with Fix |
| --: | --: |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |
| 1,081.97 | 269.92 |
| 1,081.97 | 2,972.11 |
| 1,081.97 | 2,972.11|
| 1,081.97 | 2,972.11 |
| 1,081.97 | 2,972.11 |
| 1,081.97 | 2,972.11 |
| 1,081.97 | 2,972.11 |
| 1,081.97 | 1,452.73 |
| 1,081.97 | 0.0 |
| 1,081.97 | 0.0 |

The sum of the curves is much the same, which I think supports the idea that the P2H demand was being averaged throughout the whole year.

**Comment by DorinevanderVlies** [comment] 2021-02-08 07:52
> @DorinevanderVlies I'm going to assign this issue back to you: would you mind checking that the fix has the desired effect? If so, this can be closed and I'll push the change to production.

That's quick! It works as I expect is should. :-)

**Comment by antw** [comment] 2021-02-08 13:15
> It works as I expect is should.

Perfect, thanks! The fix is on its way to production.

**Closed by antw** 2021-02-08 13:15 UTC
Labels: Bug
