### ISSUE TITLE
Merit seems to use the wrong interconnector capacity for local datasets

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#3148] opened 2019-10-07 10:35 UTC
I tested this in an empty scenario for Hengelo on the Beta server.

The interconnector capacity as displayed in the merit order table differs from the one set by the slider (see image below). It appears like the merit order table displays the *national* interconnector capacity (for NL in this case)

![Screenshot 2019-10-07 at 12 20 48](https://user-images.githubusercontent.com/4669028/66304726-2dd85400-e8fe-11e9-8d0b-ec86a269cba8.png)

Assigning @MartLubben . Reassign if you wish.

**Comment by antw** [comment] 2019-10-07 11:37
This is a duplicate of quintel/etsource#1757 which has been open for quite some time. I'll put it in my backlog so we can hopefully find some time to deal with it once and for all.

**Closed by antw** 2019-10-07 11:37 UTC
