### ISSUE TITLE
Primary CO2 emissions of Final demand chart has units of ZJ (instead of Mton)

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etmodel#1916] opened 2015-09-29 08:49 UTC
The `Primary CO2 emissions of final demand` chart now has alarming units of ZJ (10ˆ21 J), while it should have units of mass, probably Mton.

![screen shot 2015-09-29 at 10 43 00](https://cloud.githubusercontent.com/assets/14106387/10159230/75f304b2-6697-11e5-906c-d1ffdd7d3ea6.png)

@antw , could you verify and change this?

**Comment by jorisberkhout** [comment] 2015-09-29 08:54
Duplicate of https://github.com/quintel/etmodel/issues/1886.

**Comment by ChaelKruip** [comment] 2015-09-29 09:03
Closing because duplicate.

**Closed by ChaelKruip** 2015-09-29 09:03 UTC
