### ISSUE TITLE
Creating saved_scenarios links for featured scenarios and removing them as presets from ETSource

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#3434] opened 2020-07-06 12:12 UTC
As just discussed in the team meeting today, we would like to create saved_scenarios-links for featured scenarios and remove the ad-files from ETSource. It would be nice to combine this improvement with the featured scenario update, on which @MartLubben is working at the moment.

The reasons for this and possible approaches can be read in this BC todo: https://3.basecamp.com/3797409/buckets/16975857/todos/2641700236 As not everybody has been added to this project I'll add Anthony's comment below.
@noracato @antw I have some questions for you:

- Which approach do you prefer?
- How much time do you think this would take?
- Is it possible to combine this @MartLubben 's update (to pick this up the coming 1,5 week) or should we not hurry?

@antw's messages on BC:
_______
Move featured scenarios to be a saved_scenario links has two advantages:

1. It would make it easier to migrate these scenarios, since they'd be updated by the normal DB migration.
2. We can represent more complex scenarios. Presets are capable of storing everything a database scenario can, except uploaded curves. Having one way of doing things (the DB) avoids this problem.

There is one small gotcha: we need to be sure the scenario IDs are the same for production and staging, so that the references in ETModel work correctly in both environments. That, or we need a way to configure which scenarios are shown in the preset scenarios list by environment.

I'm imagining a YAML file like:
```
- national_scenarios:
  # 100% duurzame energie in 2030
  - production: 1000  # ID of the scenario on production ETE
    staging: 2212     # ID of the scenario on staging ETE
  # Net voor de Toekomst - Generieke sturing
  - production: 1001
    staging: 2213
  # ...
- scenarios_for_provinces_and_regions:
  # ..
```
An alternative might be to add a new table to ETEngine: "featured_scenarios" with a couple of columns:

- scenario_id – Self-explanatory
- key – A unique (string) key which identifies the scenario.

ETEngine would still be responsible for sending the list of featured scenarios to ETModel (as it does today with presets), rather than ETModel defining them in a config file. ScenarioController#create/Scenario would need to be able to receive the featured scenario "key" to create a clone of the preset.

**Comment by antw** [comment] 2020-07-06 12:22
> Which approach do you prefer?

I'm liking the featured_scenarios table option myself. It feels quite simple, and ETModel will continue to work largely as it does today.

Specifying the scenarios in an ETModel config (my original suggestion) makes the deploy workflow more complicated:

1. Add the scenario in a migration.
2. Look up the scenario IDs.
3. Add them to the ETModel config and commit.
4. Deploy ETModel.

This feels cumbersome. A `featured_scenarios` table means ETModel needs virtually no changes; we'll just update the API in ETEngine to use this table instead of Atlas presets.

We'll need to create these scenarios in a migration anyway; it'll be trivial to also tell ETEngine that it should be "featured" and shown on the ETModel front page.

> How much time do you think this would take?

Probably 2-3 days to:

1. Add the new table and model in ETEngine.
2. Update the way we clone scenarios to remove support for presets and add features scenarios.
3. Convert the current presets to scenarios.
4. Remove Presets from Atlas and ETEngine.
5. Perhaps find a way to automate the creation of a migration (so that the scenario is created on production when deployed).

> Is it possible to combine this @MartLubben 's update (to pick this up the coming 1,5 week) or should we not hurry?

I'm focused on CCUS but, as this is going to continue for the foreseeable future (and I wouldn't mind a distraction), I'm happy to pick this up in the next week or so. I'd need to be sure this is okay with @ChaelKruip and @michieldenhaan first.

**Comment by ChaelKruip** [comment] 2020-07-06 14:04
>  I'd need to be sure this is okay with @ChaelKruip and @michieldenhaan first.

I'm fine with you picking this up as a distraction if @michieldenhaan has no objections :)

**Comment by michieldenhaan** [comment] 2020-07-07 07:03
Fine with me as well!

**Comment by antw** [comment] 2020-07-07 12:23
I've been thinking about this quite a bit, and now have some doubts. We have a couple of options and – as they all have various disadvantages – I'd appreciate the input of @quintel/core.

1. Keep the current Preset .ad files.
2. Add "featured scenarios" (database table) in ETEngine.
3. Add "featured scenarios" (config or database table) in ETModel.
4. Use saved scenarios feature in ETModel.

Part of my doubts stem from the fact that Nora and Steven just spent a lot of time extracting (mostly static) data from ETModel into YAML files (with YModel). Many of the advantages of using static files for the ETModel data are also true for presets.

### 1. Keep the current Preset .ad files

Self-explanatory. @DorinevanderVlies and @MartLubben expressed their dislike for presets in the team meeting yesterday.

* Clearly they're a pain to migrate when ETSource is updated; whereas ETEngine benefits from automated migrations, I'm guessing presets are done by hand.

* We can't attach export price curves to presets.

Are there other problems of which I'm not aware? There was a suggestion that it's annoying to create preset files, but I'm not sure I understand why. [The ETEngine scenario list](https://beta-engine.energytransitionmodel.com/inspect/1324047/scenarios) has an "export" link next to each scenario, which should produce a fully-functional preset file ([example](https://beta-engine.energytransitionmodel.com/inspect/1324047/scenarios/1324048.ad)). To this you must add a title and description, but otherwise it should be ready to commit to ETSource.

Presets do have a big advantage over the other options: they're linked to the ETSource version. We know presets are valid against the current version of ETSource (otherwise the tests would fail) and they're trivial to deploy: import an ETSource commit and ETEngine/ETModel immediately have the correct version.

### 2. Add "featured scenarios" (database table) in ETEngine

With this option you'll visit ETEngine and open a scenario from the scenario list. A button "Feature this scenario" will allow you to add a title and description for the scenario, and it'll appear on ETModel once its caches are cleared.

This has some advantages:

* Database scenarios are automatically migrated; no more hand-editing scenarios with each project.

* We can add different titles and descriptions for Dutch and English (in fact, presets already support multilingual descriptions, but I suspect this feature is not well-known).

* We can create a simple migration which will tell the production copy of ETEngine to fetch a **new** featured scenario from beta when deploying:
  ```ruby
  class SyncRenewableFeaturedScenario < ActiveRecord::Migration[6.0]
    def up
      # Tells ETEngine to go to beta and fetch the preset called
      # "100_percent_duurzame_energie" and create a copy.
      SyncFeaturedScenario.call(
        'https://beta-engine.energytransitionmodel.com',
        '100_percent_duurzame_energie'
      )
    end
  end
  ```

The disadvantages include:

* Error-prone syncing from beta to production when a featured scenario is updated. QIs must remember to create a migration when they update a featured scenario, ensuring that it is copied to production when deployed. If you forget to create a migration, production will deploy with an old copy of the featured scenario.

* Featured scenarios would no longer be automatically checked for correctness by ETSource, however we could add a similar check in ETEngine.

### 3. Add "featured scenarios" (config or database table) in ETModel.

Whether in the ETModel database or in a config file, this option has us "protecting" scenarios in ETEngine but not having any concept of a featured scenario there. Instead we'll use a config file (or database table?) where you'd list the scenario IDs which should be featured.

This has pretty much all the disadvantages of option 2 ("featured scenarios in ETEngine"), with no clear upside.

### 4. Use saved scenarios feature in ETModel

With this option we'll have a "Quintel" ETM account which will be responsible for saving scenarios, which then appear as featured scenarios.

There are some benefits:

* Scenarios get migrations, as in options 2 and 3.

* Titles and descriptions are stored in ETModel (but would not be multilingual, unless we add support for this).

* We could use [ActionText](https://edgeguides.rubyonrails.org/action_text_overview.html) (the same editor used by Basecamp) to format descriptions and even attach images, *if* we add this to ETModel at a later date.

* We could show [a version history](https://3.basecamp.com/3797409/buckets/6180918/messages/2612861360) of a featured scenario, allowing a user to load an older version should they desire. *In practice* I doubt this is a significant advantage; [it's quite rare that presets are updated](https://github.com/quintel/etsource/commits/master/presets/quintel) and most of them are automated migrations which would not be visible to users.

* Conceptually it "feels" like featured scenarios are an ETModel feature: other applications don't know or care about them, so why should they be part of ETEngine or ETSource?

The disadvantages are:

* It is still troublesome to sync scenarios between ETEngine beta and production. "Error-prone syncing" described for option 2 still applies.

* We'd now *also* have to sync saved featured scenarios between ETModel beta and production. Alternatively, a QI must alter them by hand after the deploy (not a good idea, IMO).

---

At this stage, I'm not actually convinced we should push ahead with this. We're trading some of the advantages and disadvantages of presets for a different set of advantages and disadvantages; but I don't think it's a clear upgrade from the status quo.

**Comment by ChaelKruip** [comment] 2020-07-08 12:23
Thanks for the in-depth analysis! Very clear and well laid out :)

> At this stage, I'm not actually convinced we should push ahead with this.

I concur. At some point, option 4 seems promising but right now we have more pressing issues IMO.

**Comment by ChaelKruip** [comment] 2020-07-08 12:24
Closing this. Please re-open if you disagree!

**Comment by marliekeverweij** [comment] 2020-07-10 14:07
Opening this issue again!

For the II3050 preset scenarios we have to be able to add a electricity price import curve and that's currently not possible with the presets on ETSource. So I think we do have to consider other options!

See: https://github.com/quintel/etsource/pull/2320

**Comment by MartLubben** [comment] 2020-07-10 14:51
I probably do not understand the full complications, but what if the preset scenario buttons @LIVE and @BETA always links to the LIVE URL? 

Isn't it true that the scenario's will always be migrated after a deploy, because they are 'protected'? We do not need the presets buttons on BETA to link to a beta scenario. I have never used them. Maybe we do want copies of the presets on BETA to check before a deploy, but a scenario ID is enough. We do not need the preset scenario buttons to link to a BETA version. Does this make the problem easier?

**Comment by antw** [comment] 2020-07-10 15:22
> Does this make the problem easier?

Yes, if we don't have to sync settings between beta and production, because beta *has no* featured scenarios, that certainly makes things easier.

> We do not need the presets buttons on BETA to link to a beta scenario. I have never used them.

I believe presets on beta are frequently used for testing before deploying; they're useful for checking that changes made haven't radically altered the outcomes of the presets. I'm not sure what is meant by "a scenario ID is enough". How would we test (featured) scenarios on beta before deploying?

For deploy testing, it's not trivial to copy scenarios from one server to another as you need the user values, balanced values (not exposed in the user interface), flexibility order, heat network order, and any attached curves. It's not realistic to believe people will copy all of this while doing their beta testing.

Since 1st January, there have been 589 scenarios created on beta using one of the presets.

**Comment by marliekeverweij** [comment] 2020-07-13 09:45
> I believe presets on beta are frequently used for testing before deploying; they're useful for checking that changes made haven't radically altered the outcomes of the presets. I'm not sure what is meant by "a scenario ID is enough". How would we test (featured) scenarios on beta before deploying?

Yes, good point Anthony. The featured scenarios on beta are indeed used for deploy testing! So I think that the featured scenarios should be available on production ánd beta.

> For deploy testing, it's not trivial to copy scenarios from one server to another as you need the user values, balanced values (not exposed in the user interface), flexibility order, heat network order, and any attached curves. It's not realistic to believe people will copy all of this while doing their beta testing.

I agree, this takes a lot of effort.

I would be in favor of implementing option 4: Use saved scenarios feature in ETModel, as it feels the most logical to me! We do have to think about the syncing between beta and production, as the scenarios should have exactly the same start values. I am trying to understand the complexity. From my viewpoint there are two moments when a scenario is updated:

- The scenario changes conceptually because of new insights (f.e. heat network merit order is adjusted)
I guess these changes will be complex to automatically sync between beta and production. However, as you mention updating featured scenarios are not updated often, so this could possibly be done by hand on beta and production by a QI.
- The scenario changes with a migration because of ETM improvements
Isn't this automatically synced when the migrations are done on both beta and production?

Is it an idea to build in checks (on mechanical turk?! or somewhere else?) to check all start values (user values, balanced values, flexibility order, heat network order, and any attached curves) between the featured scenario on beta en production?

**Comment by michieldenhaan** [comment] 2020-07-13 15:05
> I probably do not understand the full complications, but what if the preset scenario buttons LIVE and BETA always links to the LIVE URL?

This is an interesting suggestion. What Mart means I think is that we create copies of PRO's preset scenarios on BETA and write down the scenario numbers. For deploys, we could compare the presets on PRO with the scenario numbers on BETA we've written down. This is a bit inconvenient but it does allow us to solve this issue in a very simple way. So it may be worth it. 

A preset can simply become a 'regular' scenario that we choose to highlight (i.e. just a link to a regular saved_scenario or scenario number). In fact, we could link to the PRO scenario numbers on PRO and to the BETA copies on BETA. 

One downside is that if we decide to alter the slider settings of the presets on PRO _manually,_ we have to make sure these changes are also applied to the copies on BETA. However, we rarely ever do this. AFAIK the only changes we make to presets are migrations and these are applied to the copies on BETA as well. So it feels a bit like a waste of time to develop some fancy new method that guarantees that the scenarios on PRO and BETA are always the same. Maybe we can add some specs to check this?

**Comment by MartLubben** [comment] 2020-07-13 18:23
@michieldenhaan explains what I was thinking. Let the current preset scenario buttons (LIVE and BETA) link to existing LIVE URLs, for example the II3050 Regional scenario: https://pro.energytransitionmodel.com/saved_scenarios/9184

In addition, we currently do not have a BETA copy of these II3050 scenario's. I think we should have copies at BETA of the presets. A simple solution is to write down the links to the copies and check them before the deploys. This can be a simple table : 
| LIVE LINK | BETA LINK|

**Comment by antw** [comment] 2020-07-14 11:48
> Let the current preset scenario buttons (LIVE and BETA) link to existing LIVE URLs, for example the II3050 Regional scenario: pro.energytransitionmodel.com/saved_scenarios/9184

Sorry, but I don't feel like this is a viable option. The list of features scenarios will reside in a live/production database; the beta/staging servers do not have access to these. While we could expose the list through an API, this would mean the list of featured scenarios is created differently depending on the environment: from a database in production, from a JSON API in staging. I feel this defeats two of the principles of a staging environment:

* To be as close a reproduction of production as possible.
* To be isolated from production, so that the two environments do not influence each other.

> In fact, we could link to the PRO scenario numbers on PRO and to the BETA copies on BETA.

This is option 4: "Use saved scenarios feature in ETModel". Production and staging would have copies of the scenarios in ETEngine, and their own ("featured") saved scenarios in ETModel.

The only problem with this is keeping them in sync. Today, adding or changing a preset is reflected as soon as we deploy a new version of ETEngine and ETSource. With option 4, QIs would have to keep track of changes made to featured scenarios on staging, and repeat those changes in production when we deploy (the scenarios would of course still benefit from automated migrations in ETEngine). We could solve this *somewhat* by requiring that such scenarios are updated only with migrations.

**Comment by MartLubben** [comment] 2020-07-14 12:24
@antw I will not dare to challenge the principles of the staging environment and will follow your expert opinion. ;-) 

Conclusion: Option 4 is the most promising for now. 

@antw Do you agree? How much time is needed do you think? 2-3 days?

**Comment by antw** [comment] 2020-07-14 12:38
> @antw Do you agree? How much time is needed do you think? 2-3 days?

Roughly, yes. 🙂

**Comment by MartLubben** [comment] 2020-07-14 12:46
@ChaelKruip Is @antw allowed to spend 2-3 days on option 4?

**Comment by antw** [comment] 2020-07-21 14:47
@quintel/core: I'm working on this now, and I had a thought: would it be nice to be able to set a locale-specific title and description for featured scenarios?

Saved scenarios have only one title and description, so it isn't possible to provide separate versions for English and Dutch readers. As a large part of our intended audience is in the Netherlands, we have defaulted to writing preset tiles and descriptions in Dutch. However, I think having English language alternatives would be nice for growing our audience and appealing to would-be clients outside of the Netherlands (I'm thinking Northern Ireland, etc).

This feature would slightly complicate things by having to store the description and title differently for featured scenarios. I'm leaning towards believing this is worth it, but would be curious what everyone else thinks.

**Comment by ChaelKruip** [comment] 2020-07-21 16:16
> This feature would slightly complicate things by having to store the description and title differently for featured scenarios. I'm leaning towards believing this is worth it, but would be curious what everyone else thinks.

I agree that it might be worth it, if it does not take you much extra time at this point.

**Comment by marliekeverweij** [comment] 2020-07-31 14:45
Let's close this issue! 🥇

**Closed** 2020-08-05 11:28 UTC
Labels: Clean up

**Comment by marliekeverweij** [comment] 2020-08-05 11:34
I guess we want to add the II3050 scenarios to BETA as well for deploy testing. We could also add them to BETA when we need them :)

> Anthony: The only problem with this is keeping them in sync. Today, adding or changing a preset is reflected as soon as we deploy a new version of ETEngine and ETSource. With option 4, QIs would have to keep track of changes made to featured scenarios on staging, and repeat those changes in production when we deploy (the scenarios would of course still benefit from automated migrations in ETEngine). We could solve this somewhat by requiring that such scenarios are updated only with migrations.

@antw, did you implement your mentioned solution: only updating these scenarios with a migration?

> Michiel: So it feels a bit like a waste of time to develop some fancy new method that guarantees that the scenarios on PRO and BETA are always the same. Maybe we can add some specs to check this?

This is also a possibility.

@antw I am curious what you think!

**Comment by antw** [comment] 2020-08-05 11:49
> @antw, did you implement your mentioned solution: only updating these scenarios with a migration?

No. At this time I leaned towards doing what [Michiel](https://github.com/quintel/etmodel/issues/3434#issuecomment-657614976) and [Mart](https://github.com/quintel/etmodel/issues/3434#issuecomment-657717294) suggested, of having no connection between staging and production.

The scenarios *can* be updated by writing migrations – though we'd have to target the specific (different) IDs in each environment – or you can log into the info@ account (I have the password) and update them manually using the normal ETModel interface.

> > Maybe we can add some specs to check this?
> 
> This is also a possibility. @antw I am curious what you think!

Sure, we can probably do this. But the scenarios on staging and production are not always guaranteed to be the same; changes that have been made on staging will not always be on production yet. It would probably be better to have Mechnical Turk tests for the featured scenarios, but presently Turk runs only against staging.

**Comment by marliekeverweij** [comment] 2020-08-05 12:20
> No. At this time I leaned towards doing what Michiel and Mart suggested, of having no connection between staging and production. The scenarios can be updated by writing migrations – though we'd have to target the specific (different) IDs in each environment – or you can log into the info@ account (I have the password) and update them manually using the normal ETModel interface.

Okay clear!

> It would probably be better to have Mechnical Turk tests for the featured scenarios, but presently Turk runs only against staging.

Yes, that is also what I was thinking. Is it a lot of effort to run MT against production as well? Then we can simply add tests to check the featured scenarios on pro and beta

**Comment by antw** [comment] 2020-08-05 12:24
> Is it a lot of effort to run MT against production as well?

I don't think so; it should be quite easy. We'd likely need:

* a separate "production" branch for Mechanical Turk,
* a config file to specify the IDs to the featured scenarios on staging and production,
* adjustments to the Semaphore config to be able to run against production.
