### ISSUE TITLE
"heating_households" group does not balance

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3224] opened 2020-02-03 15:30 UTC
When updating a households space heating & hot water slider setting, the "heating_households" group does not balance which results in an error page on BETA.

This issue relates to some extent to https://github.com/quintel/etmodel/issues/3110:

> I think this is related to the fact that we've hid the coal and crude oil heater sliders for some datasets. The balancing mismatch is exactly equal to the share of heater_coal and heater_crude_oil. The reason we hide these sliders is that for NL and derived datasets their value is either 0 or close to 0 (< 0.5%) and they clutter the slider group.

The strange thing is that updating the district heating slider seems to solve the balancing issue.

![image](https://user-images.githubusercontent.com/5946498/73665692-d37bb400-46a1-11ea-9166-dca9f0df3bf1.png)

**Comment by antw** [comment] 2020-02-03 16:42
I tried setting the heat pump share to 100% in a new scenario, but cannot reproduce this myself. Was your scenario created using a preset or saved scenario?

**Comment by redekok** [comment] 2020-02-03 16:47
That's quite strange..

> Was your scenario created using a preset or saved scenario?

No, I created a blank 2050 scenario for the Netherlands. You did try to reproduce this error on BETA (and not on LIVE), right?

**Comment by antw** [comment] 2020-02-03 18:24
Wasn't signed in, so I didn't see the error message. 🤦‍♂

I can reproduce it now. It seems only to be a problem if the HP slider is moved to 100% and _hasn't_ been moved previously.

**Comment by michieldenhaan** [comment] 2020-02-04 08:58
For me it occurs when touching just about any slider for the first time (except the district heating slider). E.g. setting the electric heater to 23%:

![beta-pro energytransitionmodel com - Energy Transition Model - Your free, independent, comprehensive, fact-based scenario build… 2020-02-04 09-54-50](https://user-images.githubusercontent.com/32056448/73729025-9dd3db00-4734-11ea-8eac-4a38cd998146.png)

But also for the gas burner, wood pellet stove etc. I think it has something to do with the oil/coal burner share being non-zero and hidden.

The same issue might be present on PRO?

**Comment by antw** [comment] 2020-02-04 16:52
I don't think this is related to the crude oil or coal shares. The error message shows the default shares of those technologies only because it is unable to auto-balance the group.

The cause is the 1e-7 share given to the network gas technology. The balancer in ETModel seems to be assigning 0.0000001 to that technology even though 100% is already assigned to the heat pump (or whatever slider you move to 100%). I'm still trying to find out why this is the case; it's not broken on PRO, and the balancing code hasn't been changed in eight years. 😧

**Comment by michieldenhaan** [comment] 2020-02-05 09:14
I'm not sure why, but if I change the ``output.useable_heat`` of the ``households_space_heater_combined_network_gas`` to 1.067 (value on PRO) instead of 1.07 (value on BETA) the error disappears on my local machine.

The change from 1.067 to 1.07 happened here: https://github.com/quintel/etsource/commit/d90562e5756158c738d007d100d0717f5a354d22#diff-cbc9d23b2181fa67fd28ac44e40ec4c6

**Comment by ChaelKruip** [comment] 2020-02-05 09:43
> I'm not sure why, but if I change the output.useable_heat of the households_space_heater_combined_network_gas to 1.067 (value on PRO) instead of 1.07 (value on BETA) the error disappears on my local machine.

Interesting find! 🤓

**Closed** 2020-02-05 16:05 UTC
Labels: Bug, Sliders

**Comment by antw** [comment] 2020-02-05 16:16
I'm hoping this is now fixed. 🤞

I believe the change in the default values of the heating technologies caused a floating point error to be rounded up to 0.000001 (the level of precision we use internally for sliders) whereas previously it was being rounded down.

On beta the sum of the share group was adding up to 100.000001, but on production it was 99.999999. Now it adds up to exactly 100.

Please reopen if this occurs again.
