### ISSUE TITLE
For the import of natural gas the network_gas_output_curve is non-zero while there is no demand

### ISSUE THREAD

**Issue by redekok** [quintel/etmodel#3354] opened 2020-05-28 08:18 UTC
For [this scenario](https://pro.energytransitionmodel.com/scenarios/761816) something strange seems to be happening:

- According to the network gas production chart, natural gas is imported in this scenario.
- According to the future energy flows sankey, there are no natural gas flows in the scenario.
- According to the future energy imports chart, no natural gas is imported in this scenario.
- There is 100% green gas in the network.

The network gas production chart seems to contradict the other charts/numbers. Could anybody explain this to me?

![image](https://user-images.githubusercontent.com/5946498/83116639-577ffe80-a0cc-11ea-8caa-b4b3eda11be4.png)

![image](https://user-images.githubusercontent.com/5946498/83115797-336fed80-a0cb-11ea-8349-aa2b2ed58926.png)

![image](https://user-images.githubusercontent.com/5946498/83115863-4a164480-a0cb-11ea-964a-696ed59871d4.png)

**Comment by antw** [comment] 2020-05-28 09:16
I have a pretty good idea why this is, and the fix should be easy. Before I push it to beta (and provide an explanation) I want to test with your scenario a bit more to be sure that I'm understanding it correctly. I should have an update later today.

**Comment by antw** [comment] 2020-05-28 12:19
> I want to test with your scenario a bit more to be sure that I'm understanding it correctly.

Scratch that. This doesn't appear to be a problem for a default scenario, and the above scenario has 450 inputs; I don't have a week to figure out which combination of inputs cause this. 😛

I believe the issue is that the (electricity?) merit order or household / building heating causes a change in the supply and demand of network gas. Here's the flow of execution:

1. First graph calculation.
2. Electricity / heat network merit order, and household / buildings heating.
3. Network gas / H2.
4. Second graph calculation.

It's fine for step 2 to change the amount of network gas / H2 used because those modules will set the new demand on the relevant nodes. However, I think they may cause different flows _elsewhere_ in the graph (maybe green gas?), on nodes which _do not_ participate in merit, which means that step 3 may be calculated with some incorrect demands.

I've moved the calculation of network gas and H2 to be after the second graph calculation and all of the network gas and H2 demands and curves now match exactly.

**Comment by antw** [comment] 2020-05-28 12:43
I'm going to reopen this. On both production and beta, with a default scenario there is a mismatch between the gas import node demand and the curve value:

| Environment | Output of natural gas | Sum of curve * 3600 | Diff |
| :-- | --: | --: | --: |
| Production | 1,254,794,996,003.9194 | 1,267,653,498,153.2156 | -12,858,502,149.296143 |
| Staging before fix | 1,259,772,401,886.1538 | 1,272,137,841,051.8855 | -12,365,439,165.73169 |
| Staging **after fix** | 1,259,772,401,886.1538 | 1,270,507,922,777.976 | -10,735,520,891.822266 |

It's not a big difference, but it's enough certainly not to be due to floating point errors. The import curve does not use the demand of the import node; rather it looks at the balance of supply and demand. Whenever there is more demand than supply, the import curve will have a value. If the sum of the import curve different from the demand of the node, it means that the graph and network gas calculations disagree.

Three possibilities come to mind:

* There could be a code error. However, there's no mismatch in the H2 calculation, so I think this is less likely (although certainty not impossible as there's much more use of network gas than H2 in a default scenario).
* It could be that we have some curves which don't sum to unity (the ETSource specs apparently has not been updated to check weather curves)
* Somewhere in the graph we're introducing network gas without including it in the time resolved network gas calculation.

**Comment by michieldenhaan** [comment] 2020-05-28 13:31
I think there's two things going here:
First of all, there's this issue: https://github.com/quintel/etsource/issues/2144. We currently do not take into account the `output_of_loss` of `energy_treatment_natural_gas` as a time-resolved demand. This means that network gas demand in the graph is higher than time-resolved demand.

Secondly, we have the dreadful `energy_mixer_for_gas_power_fuel` which mixes network_gas with oil and bio oil. Industrial CHPs use this power fuel mix. The industrial CHPs are included in time-resolved demand but the `gas_power_fuelmix` they consume isn't 100% network gas (for NL the default share is 92% network gas, 8% oil). The time-resolved calculation doesn't know about this mix, so treats the CHP demand as 100% network gas demand. This means that time-resolved demand is higher than the demand in the graph.

If I set this fuel mix to 100% network gas and take into account the treatment losses, the diff is very close to zero for a default NL scenario.

As a side note:
For hydrogen, we have 1 clear 'back up' node in case demand > supply: the `energy_imported_hydrogen_backup` node. For network gas this isn't the case: in the graph any network gas deficit comes from `energy_import_natural_gas`, `energy_regasification_lng` and `energy_distribution_greengas` depending on the network gas mix. The first node has `network_gas.type = import` whereas the other two have `network_gas.type = producer`. Could this be part of the problem for Roos' scenario? If 100% of network gas is green gas and gas demand > gas supply, the hourly calculation should 'add' a green gas demand to make sure that total network gas demand and supply are equal. But `energy_import_natural_gas` is the only `import` node, so any deficit is filled in with natural gas? In any case, @antw's fix should solve this.

**Comment by antw** [comment] 2020-05-28 13:43
> Could this be part of the problem for Roos' scenario? If 100% of network gas is green gas and gas demand > gas supply, the hourly calculation should 'add' a green gas demand to make sure that total network gas demand and supply are equal. But energy_import_natural_gas is the only import node, so any deficit is filled in with natural gas? In any case, @antw's fix should solve this.

Yes exactly. The fix (already published) works perfectly for Roos' scenario (when tested on beta); the import demand and curve agree that there is no imported natural gas.

**Comment by michieldenhaan** [comment] 2020-05-28 13:59
I think we can close this then. Roos' scenario does not have industrial CHPs nor natural gas treatment demand (and losses) which means that the demand in the graph and time-resolved demand should match exactly. Do you agree @redekok, @antw?

I'll make a separate issue about the gas power fuelmix.

**Closed** 2020-05-28 15:40 UTC
Labels: Question
