### ISSUE TITLE
Removing all heat supply to heat network causes scenario not to load

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#2284] opened 2016-10-24 15:15 UTC
I discovered this issue while tweaking a scaled scenario for Paddepoel in Groningen. This area has no heat network currently, so I wanted to remove all demand and supply of heat on the central heat network. As expected, I had no problems getting rid of heat demand from the heating grid for either `present` or `future` As soon as I remove the final converter supplying heat to the heat network, however, the scenario no longer loads. 

As you can see, even an infinitesimal amount of heat supply suffices (FYI: total space heating demand is 15.6 TJ):
![image](https://cloud.githubusercontent.com/assets/308563/19651321/b438e080-9a0c-11e6-939d-23e139a0c660.png)

setting this to:
number_of_energy_heater_for_heat_network_waste_mix: 0.0

and/or:
number_of_energy_heater_for_heat_network_waste_mix_present: 0.0

causes it to freeze or not load (depending on how you set it to zero, in the scenario file or by using the slider).

**Background**
[This scenario](https://beta-pro.energytransitionmodel.com/scenarios/592667) was created by scaling to 495 households from a NL 2035 blank scenario (no industry or agriculture, yes energy sector), except for the _future_ supply of heat and power, which was created by scaling a SER 2023 Energieakkoord scenario to 495 residences in the same way. 

Notifying @DorinevanderVlies

**Comment by antw** [comment] 2016-10-25 14:24
Looking at `energy_heat_network_steam_hot_water`, when all of the suppliers have no demand the dependent and inversed_flexible links don't get a `share` calculated:

![screen shot 2016-10-25 at 15 08 40](https://cloud.githubusercontent.com/assets/4383/19689335/f412cfd2-9ac4-11e6-88de-b35bc57db3da.png)

This is because [only "constant" links are automatically assigned a share of 0.0](https://github.com/quintel/etengine/blob/013be50ea242fd78288479be66d6c3336d314514/app/models/qernel/link.rb#L192-L195) when they have no energy flowing through them. I don't know the historical reasons behind this.

For comparison, here's a default 2040 NL scenario:

![screen shot 2016-10-25 at 15 09 08](https://cloud.githubusercontent.com/assets/4383/19689415/3588906e-9ac5-11e6-84da-17070ec587a2.png)

Recursive factor assumes that a link with no share [should be treated as if it has a share of 1.0](https://github.com/quintel/etengine/blob/013be50ea242fd78288479be66d6c3336d314514/app/models/qernel/recursive_factor/base.rb#L154-L161). Again, I don't know why. 😞 

The result is the recursive factor calculation for `sustainability_share` ends up in an infinite loop:

1. agriculture_locally_available_steam_hot_water
2. energy_heat_network_steam_hot_water
3. agriculture_unused_local_production_steam_hot_water
4. agriculture_locally_available_steam_hot_water
5. ...
6. ...

I suspect the default scenario only avoid this loop because the share of "agriculture unused local production steam / hot water" is zero. Perhaps it would also get caught in a loop if there was energy flowing through that link?

--

Possible solutions:

1. In recursive factor, assume a link with no share actually has a share of 0.0 instead of 1.0.

2. Change the way link shares are calculated so that dependent and inversed_flexible links are also assigned a share of 0.0 when their share is blank. I *feels* like something which should be done, but I'm hesitant since I don't understand why this behaviour is only enabled for constant links... there must have been a reason.

Neither of these address the possibility that the same infinite loop will be triggered if the "unused local production" link has energy flowing through it. Recursive factor can't cope with loops in the graph.

**Comment by ChaelKruip** [comment] 2016-10-25 15:34
> In recursive factor, assume a link with no share actually has a share of 0.0 instead of 1.0.

Can this work if all energy flows are zero? Would that mean that all shares are zero and therefore don't add up to 1.0 anymore?

> Change the way link shares are calculated so that dependent and inversed_flexible links are also assigned a share of 0.0 when their share is blank. I feels like something which should be done, but I'm hesitant since I don't understand why this behaviour is only enabled for constant links... there must have been a reason.

Is this easy to do? If so, can you push a branch with that change so we can assess possible fall-out?

> Neither of these address the possibility that the same infinite loop will be triggered if the "unused local production" link has energy flowing through it. Recursive factor can't cope with loops in the graph.

Would this also happen if the "unused local production" has energy flowing through it in the future year? 

[My scenario](https://beta-pro.energytransitionmodel.com/scenarios/593128) works like a charm it seems:
![energytransitionmodel](https://cloud.githubusercontent.com/assets/1303760/19692699/239c5f2a-9ad9-11e6-95e7-9bff60e5ae62.png)

**Comment by antw** [comment] 2016-10-25 16:25
> My scenario works like a charm it seems:

If you follow the links to the right, one has a share of zero which prevents recursive factor from looping back to `energy_heat_network_steam_hot_water`:

**`agriculture_locally_available_steam_hot_water`:**

![screen shot 2016-10-25 at 17 21 45](https://cloud.githubusercontent.com/assets/4383/19694537/a91c6106-9ad7-11e6-8341-560b810b137d.png)

**Comment by ChaelKruip** [comment] 2016-10-26 08:41
> The result is the recursive factor calculation for sustainability_share ends up in an infinite loop

Do you mean that if there is no energy flow through the heat network, both shares are 1.0, and the calculator goes into a loop?

> If you follow the links to the right, one has a share of zero which prevents recursive factor from looping back to energy_heat_network_steam_hot_water:

Right. 

> Perhaps it would also get caught in a loop if there was energy flowing through that link?

> Neither of these address the possibility that the same infinite loop will be triggered if the "unused local production" link has energy flowing through it. Recursive factor can't cope with loops in the graph.

I think this works in all situations where there is non-zero flow through the heat network because there is either a surplus in the agricultural sector (the share of `energy_heat_network_steam_hot_water` is zero) or there is a deficit and the share of `agriculture_unused_local_production_steam_hot_water` with the heat network is zero. They can't be non-zero at the same time. Does that make sense?

**Comment by antw** [comment] 2016-10-26 09:18
> Does that make sense?

:+1:

I'll create an experimental branch so that we might test: "change the way link shares are calculated so that dependent and inversed_flexible links are also assigned a share of 0.0 when their share is blank."

**Comment by antw** [comment] 2016-10-26 09:38
> I'll create an experimental branch [...]

Pushed to [quintel/etengine@set-link-nil-shares](https://github.com/quintel/etengine/tree/set-link-nil-shares).

**Comment by marliekeverweij** [comment] 2020-02-26 08:49
Is this issue still relevant? I think it's a good one to test for this deploy because of the heat network update @antw

**Comment by antw** [comment] 2020-02-26 13:37
I can't reproduce this anymore in an unscaled NL scenario. I set all dispatchable and must-run heat producers to zero, and the graph still calculates fine. It also works when scaling the scenario.

I couldn't test with the [original scenario](https://beta-pro.energytransitionmodel.com/scenarios/592667) as it uses ["adjust_scaling" inputs](https://github.com/quintel/etsource/tree/master/inputs/adjust_scaling/buildings/buildings_district_heating), which haven't been updated to reflect the heat network changes.

Do we have any plans for these old inputs? Pinging @michieldenhaan.

**Comment by michieldenhaan** [comment] 2020-02-26 15:45
> Do we have any plans for these old inputs? Pinging @michieldenhaan.

Yes, hopefully we can get rid of them soon. I'll pick that up after the deploy. 
There's another issue about that (https://github.com/quintel/etlocal/issues/126) so I think we can close this one.

**Closed by michieldenhaan** 2020-02-26 15:45 UTC
Labels: Bug
