### ISSUE TITLE
Geothermal should be added to the Sankey Energy flow overview

### ISSUE THREAD

**Issue by MartLubben** [quintel/etmodel#4211] opened 2024-03-04 08:58 UTC
Link: https://pro.energytransitionmodel.com/scenarios/1097001 
<img width="1397" alt="image" src="https://github.com/quintel/etmodel/assets/33415156/2c2226f7-8c4f-4441-acca-1c879791394b">

**Comment by kaskranenburgQ** [comment] 2024-03-07 09:24
This issue is a duplicate of issue #[2998](https://github.com/quintel/etsource/issues/2998) of the ETSource repository.

**Comment by kaskranenburgQ** [comment] 2024-03-07 10:10
As far as I can see the queries for this flow are already created, it just needs to be added in the sankey.

**Closed** 2024-03-08 16:05 UTC
Labels: Pinned, Sankey
