### ISSUE TITLE
Let's add Berenschot to the Partners section (I suppose non-paying for now)

### ISSUE THREAD

**Issue by AlexanderWirtz** [quintel/etmodel#1836] opened 2014-09-26 12:50 UTC
We may also need to add Berenschot to the reel on etmodel, but I am not sure this is relevant for non-paying partners.
See https://github.com/quintel/etcentral/issues/113

**Comment by grdw** [comment] 2017-02-10 13:32
Duplicate of https://github.com/quintel/etcentral/issues/113

**Closed by grdw** 2017-02-10 13:32 UTC
