### ISSUE TITLE
Weather conditions slide should not freeze for Sweden (and maybe more countries)

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#4000] opened 2022-08-25 07:55 UTC
A client just called me about this issue. When starting a new Sweden scenario and going to the "Weather conditions slide" the model crashes: the slide freezes and you cannot click on anything anymore.

Maybe this has to do with the FLH sliders for Sweden? The flh for inland wind are `4189.6761` and this is higher than the max value for that slider `3500`

![Screenshot 2022-08-25 at 09 50 25](https://user-images.githubusercontent.com/32833996/186607347-8d872822-f5e8-41cc-972a-140d90f94a7b.png)

**Comment by antw** [comment] 2022-08-25 08:59
A code fix is on the way to staging and will be sent to production shortly.

Ultimately, the cause is that the FLH for inland wind turbines has the following:

```
- max_value = 3500.0
- min_value_gql = present:V(energy_power_wind_turbine_inland, full_load_hours)
```

The maximum value is set to a maximum of 3500. However, in Sweden, the min value (the present value for inland turbine FLH) returns 4189.6761.

The code change will fix the page locking up, but the slider will be disabled so long as min > max.

@marliekeverweij Can you decide what you'd like to do about the slider values? Of course, reassign this as you see fit.

**Comment by marliekeverweij** [comment] 2022-08-25 09:17
We have two options for fixing this:
1. Increasing slider max to 4500
2. Changing inland wind flh for Sweden (All other countries have flh lower than 3000 for inland wind)

We used the same approach for calculating the flh for all EU datasets based on hourly profiles of Renewables Ninja. I prefer not to change this approach for one country. So I prefer to change the slider max. What do you think? Notifying @DorinevanderVlies as she calculated these flh. But everybody else is welcome to give their opinion! @quintel/core

**Comment by DorinevanderVlies** [comment] 2022-08-25 09:37
I am ok with option 1

**Comment by DorinevanderVlies** [comment] 2022-08-25 09:59
Hmmm, Renewables.ninja shows a capacity factor of ~25% for onshore wind. That would mean ~2200 flh. 
Let's see if I can track where the 4500 comes from

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/19907658/186635512-fecf835f-7c04-40ac-98ee-9a1f80d12256.png">

**Comment by marliekeverweij** [comment] 2022-08-25 10:07
Thanks @DorinevanderVlies !

**Comment by DorinevanderVlies** [comment] 2022-08-25 10:24
When I run the script I get inland flh of 2223 en offshore flh of 4189

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/19907658/186640479-872c90d4-7741-4980-bbbe-45fb0d17a4aa.png">

It seems to me that the flh of onshore wind is currently incorrect in The Swedish dataset. It should be 2223.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/19907658/186640720-b9d27016-0db3-4274-aa99-25db180be68c.png">

**Comment by AlexanderWirtz** [comment] 2022-08-25 11:15
@DorinevanderVlies that seems more realistic. I would not want to live in a country with onshore FLH of > 4500. :-)

**Comment by marliekeverweij** [comment] 2022-08-25 14:06
Thanks for the answer to this issue! I checked alll countries and found that also in the UK the flh are different:

- old - 2223.3584 for all wind turbines (this is the new SE value, so I think we mixed them up in the migration)
- new - 3174 for offshore/coastal and 2482 for inland

**Comment by AlexanderWirtz** [comment] 2022-08-25 14:09
IF we fix this, it may affect the Guidehouse scenarios for NSPWH.

**Closed** 2022-08-26 14:04 UTC
Labels: Bug
