### ISSUE TITLE
Initial network costs very different on beta and on live

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2480] opened 2017-09-08 15:50 UTC
On beta the 2013 network costs are much higher (5.87 bln euro) than on live (3.26 bln euro).

This seems to be cause by "total investment costs of various levels of the network). For details see table below.

@antw how are the tot investment costs calculated? Is there a difference in calculation for 2013 and 2017? 

**Total investment costs on live and beta (2013 and 2050)**
![image](https://user-images.githubusercontent.com/19907658/30219842-9a5b716c-94bd-11e7-81d6-22cc2de06f66.png)

**Costs beta**: 
![image](https://user-images.githubusercontent.com/19907658/30220039-3ef15ad4-94be-11e7-95fd-bdd6d7f5881e.png)

**Costs live**:
![image](https://user-images.githubusercontent.com/19907658/30220003-27c65832-94be-11e7-930a-ede677aa4086.png)

Notifying @ChaelKruip

**Comment by antw** [comment] 2017-09-08 16:56
Duplicate of https://github.com/quintel/etmodel/issues/2460?

I'm reasonably certain that this is indeed caused by the detection of peak loads. A curve which used to represent `electricity` demand now instead shows total `useable_heat` demand. I already started fixing this earlier in the week, but it's complicated by the need to have two completely separate implementations of the same thing (one for `future`/Merit-on and another for `present`/Merit-off).

**Comment by DorinevanderVlies** [comment] 2017-09-11 06:45
> Duplicate of #2460?

I think the two might indeed be correlated. This issue addresses the initial costs, #2460 the change in costs. 

> I'm reasonably certain that this is indeed caused by the detection of peak loads.

Would be nice if that fix solves both issues! Good luck!

**Comment by antw** [comment] 2017-09-18 16:58
Now on beta:

![screen shot 2017-09-18 at 17 57 49](https://user-images.githubusercontent.com/4383/30554007-f064d1f4-9c9a-11e7-9260-15b38cae737b.png)

**Closed by antw** 2017-09-18 16:58 UTC
