### ISSUE TITLE
II3050 European CO2 governance has different CO2 emission between Beta and Production

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etmodel#3502] opened 2020-11-12 15:12 UTC
Pro:
![image](https://user-images.githubusercontent.com/1303760/98957635-ae09b980-2501-11eb-8657-4260f2905d90.png)
Beta:
![image](https://user-images.githubusercontent.com/1303760/98957665-b6fa8b00-2501-11eb-87c0-f25f09731b7f.png)

It seems that the industry sector has about 10(!) MT more emissions.

**Comment by michieldenhaan** [comment] 2020-11-12 17:01
This was largely caused by an error in the scenario migration. Now fixed: Total CO2 -95.8% PRO vs -96.2% BETA.

![image](https://user-images.githubusercontent.com/32056448/98970871-bd443380-2510-11eb-8128-7f458210057a.png)

**Closed by michieldenhaan** 2020-11-12 17:01 UTC
