### ISSUE TITLE
The total excess electricity is significantly lower when P2G flexibility options are selected.

### ISSUE THREAD

**Issue by DorinevanderVlies** [quintel/etmodel#2214] opened 2016-09-08 08:13 UTC
## Problem
The total excess electricity should be (roughly) the same regardless of which flexibility options are selected.

This is the case for batteries, EV's and conversion to heat.
However, when conversion to gas is used the total excess electricity is a lot (almost 30% in the example case) lower. 

## Example
This [scenario](https://beta-pro.energytransitionmodel.com/scenarios/574680) is based on Urgenda 2030.  

- Without flexibility options excess electricity is 373 PJ (94 PJ Exported, 279 PJ curtailed)
- When maximum P2G for transport is set the excess electricity is 260 PJ (174 PJ converted to gas for transport, 87 PJ losses)
- When maximum P2G for industry is set the excess electricity is 177 PJ (177 PJ converted for industry (see #2213 for comments about losses P2G for industry) 

### No flexibility options
![image](https://cloud.githubusercontent.com/assets/19907658/18341448/52c831e2-75aa-11e6-89ec-c4afa8dc3fd2.png)

### Max P2G for transport
![image](https://cloud.githubusercontent.com/assets/19907658/18341467/60a88f14-75aa-11e6-8dc3-e28e1697b98f.png)

### Max P2G for industry
![image](https://cloud.githubusercontent.com/assets/19907658/18341482/74620d96-75aa-11e6-9a38-eaef8e608fff.png)

**Comment by ChaelKruip** [comment] 2016-09-08 09:22
Is this not just another manifestation of https://github.com/quintel/etmodel/issues/2213?

**Comment by jorisberkhout** [comment] 2016-09-08 09:25
> Is this not just another manifestation of #2213?

Yes, it is. Both are caused by an error in the gqueries that make up these charts/tables. I will push a fix soon.

**Comment by jorisberkhout** [comment] 2016-09-13 15:58
Closed by https://github.com/quintel/etengine/commit/51b74a319db3a1656d95177ea8ca2100e4b722db. I turns out that we were counting the losses in P2G twice, once in Merit and once again in the graph. This is now fixed.

One note, electricity export and curtailment are connected to the HV net. If all your excess electricity goes to export and/or curtailment, there is transport losses associated with the transport over the HV net (~4.49 %). P2G is not connected to the electricity net in the graph. Running all excess to this P2G unit therefore avoids the losses on the net. Since these network losses are not included in the excess electricity tables and charts, the amount of excess electricity effectively increases when you built P2G units. These effects are relatively small and I will open a new (not deploy critical) issue for this. A similar effect is present for the P2P options.

Closing this issue.

**Closed by jorisberkhout** 2016-09-13 15:58 UTC
