### ISSUE TITLE
Add a table with statistical data on number and duration of excess electricity events

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etmodel#2084] opened 2016-03-17 17:20 UTC
As the charts that are described in #2081 and #2082 are potentially difficult to interpret, we would like to add a table with some key parameters about the number of times there is excess electricity and the duration of the excess events. I would suggest to keep this table very simple to start with the number of events with a minimum duration of 1, 2, 4, and 8 hours.

| minimum duration (h) | # of events |
| --- | --- |
| 1 | 100 |
| 2 | 75 |
| 4 | 5 |
| 8 | 2 |

Including @AlexanderWirtz , @dennisschoenmakers and @ChaelKruip.

**Comment by jorisberkhout** [comment] 2016-04-29 15:14
I'm struggling a little with this issue. I assumed that there is a load curve which contains the amount of excess electricity per hour (in MW) and which I could process to obtain the required data. I now realise that the flexibility feature in merit is implemented in a much smarter way.

@antw could you help me out here? I would basically like to have a method that I can call from a Gquery to fill the table above with data. This method would take 1 argument (`excess_duration`), i.e. an integer expressing the minimum number of consecutive hours with excess electricity. The method would then have to return another integer expressing the number of times throughout the entire year an excess electricity event lasts at least `excess_duration` hours.

Would you be able to estimate how much time it would cost to implement such a method, @antw ?

**Comment by antw** [comment] 2016-05-03 14:36
> I now realise that the flexibility feature in merit is implemented in a much smarter way.

Is that a polite way of saying "WTF was @antw thinking with this code"? 😆 

An excess load curve might be a nice addition, I'll look into that.

Would this be excess load before or after storage? i.e. if a time step has 50kWh of excess "always on" production, but 30kWh ends up being stored in batteries, do you want the curve to report an excess of 50kWh or of 20kWh?

**Comment by AlexanderWirtz** [comment] 2016-05-04 07:23
@jorisberkhout do we also want to report on the 'volume' of these excess events and not just on the duration?

**Comment by jorisberkhout** [comment] 2016-06-09 13:34
> Is that a polite way of saying "WTF was @antw thinking with this code"? 😆

Sorry, I overlooked your comment. I would of course never say or think anything like that!

**Comment by jorisberkhout** [comment] 2016-06-09 13:36
> @jorisberkhout do we also want to report on the 'volume' of these excess events and not just on the duration?

Good point, reporting the excess volume would be a nice addition to this table.

**Comment by jorisberkhout** [comment] 2016-06-09 13:38
> Would this be excess load before or after storage? i.e. if a time step has 50kWh of excess "always on" production, but 30kWh ends up being stored in batteries, do you want the curve to report an excess of 50kWh or of 20kWh?

50 kWh. The way I think about this is that the table provides the user with insight on the duration and volume of the excess events to determine which flexibility options would be be suitable.

**Comment by jorisberkhout** [comment] 2016-06-09 13:46
> An excess load curve might be a nice addition, I'll look into that.

@grdw, could you look into this? I think this is easily calculated in `merit` as:
`excess load curve = sum(all electricity production) - electricity demand`

This curve needs to be added to the download csv, see https://github.com/quintel/merit/issues/127 for a related issue.

**Comment by jorisberkhout** [comment] 2016-06-09 13:53
The second ingredient that we need to fill the table with data is a method that is able to determine the amount of excess event of a specific duration provided by the user and the associated excess volume. I imagine this method to look like:

`number_of_excess_events(duration)`

with duration in hours. This method would go through the `excess load curve` and count the number of times that there is excess electricity for at least `duration` hours. I think we're looking for a similar implementation to the [`loss_of_load_expectation` method](https://github.com/quintel/etengine/blob/ed141dccea479b9dddbc9acc68e5f28f551b3b17/app/models/qernel/graph_api.rb#L97-L120).

**Comment by jorisberkhout** [comment] 2016-06-09 13:54
> @jorisberkhout do we also want to report on the 'volume' of these excess events and not just on the duration?

One question though, @AlexanderWirtz , which `volume` would you like to report here? The total annual volume in events with duration of at least `x` hours? Or the average volume per event of at least `x` hours? Or another volume?

**Comment by jorisberkhout** [comment] 2016-06-09 13:55
Assiging @grdw to do the merit and etengine part of it. Once those are done, I will do the etsource and etmodel part of this issue.

**Comment by AlexanderWirtz** [comment] 2016-06-14 12:59
> One question though, @AlexanderWirtz , which volume would you like to report here? The total annual volume in events with duration of at least x hours? Or the average volume per event of at least x hours? Or another volume?

Wow, good question. I guess this depends on what our options are for doing something useful with the excess volume. I would argue for highlighting these options through something like minimum ON-times, not so much volume, but that is more of a gut feeling. I realize merit has one-hour resolution, but different options require different minimum ON-times.

- P2H is pretty flexible and any excess E van go towards making H until buffers are full
- P2P is also quite flexible, although there may be some technical parameters, such as enhanced battery life, that mandate charging periods of at least half an hour to one hour. In reality, short excess events will be stored in (super)capacitors and longer ones in actual batteries
- P2G is probably not a process that can deal with very short ON-times, as that would limit efficiency and damage (high-temperature) equipment

**Comment by grdw** [comment] 2016-06-20 09:31
I'm looking into this issue right now and to rephrase: there needs to be a method available in the sandbox of ETEngine (if it's available in the sandbox does that imply that it's also available elsewhere or @antw ?) that is called:

`number_of_excess_events(duration)`

Calling this method will take the `duration` argument and compare two curves. The curve which contains all electricity production and all electricity consumption. Than there are three possible situations: 

1. production is equal to consumption 
2. production is higher than consumption, 
3. production is lower than consumption.

Should 2 and 3 both count as an excess event or is 3 loss of load and 2 the actual excess event?

Also: how do I fetch the total electricity production and consumption? Are there already methods available which I can call in the sandbox? 

And to be clear; at which scopes should this method be available? From the API? From the sandbox? As a gql? Is there any difference or is it all interchangeable?

**Comment by ChaelKruip** [comment] 2016-06-20 09:41
> Should 2 and 3 both count as an excess event or is 3 loss of load and 2 the actual excess event?

Only 2 is a real excess event.

**Comment by antw** [comment] 2016-06-20 09:58
>  there needs to be a method available in the sandbox of ETEngine (if it's available in the sandbox does that imply that it's also available elsewhere or @antw ?) that is called: [...] Also: how do I fetch the total electricity production and consumption? Are there already methods available which I can call in the sandbox?

I would imagine that the feature itself should reside in [Merit](https://github.com/quintel/merit) and not in ETEngine. See [lole.rb](https://github.com/quintel/merit/blob/master/lib/merit/lole.rb) in Merit for how we calculate loss-of-load, and [the two methods in ETEngine](https://github.com/quintel/etengine/blob/master/app/models/qernel/graph_api.rb#L97-L134) for querying this.

Getting production and consumption from a calculated merit order should be simple:

```ruby
# Curve containing total production
merit_order.participants.producers.map(&:load_curve).reduce(:+)

# Curve containing total consumption
merit_order.participants.users.map(&:load_curve).reduce(:+)
```

One thing to watch out for is that we now also have flexibility modelled in Merit (`merit_order.participants.flex`), and those load curves may contain positive or negative values. Positive indicates consumption, negative is production. The total production and consumption curves will have to be adjusted to accordingly.

**Comment by grdw** [comment] 2016-06-20 11:51
> I would imagine that the feature itself should reside in Merit and not in ETEngine

Great! And than extend the Merit order plugin in ETEngine to make use of this new feature?

> The total production and consumption curves will have to be adjusted to accordingly.

So the flexibility needs to be woven into the production or consumption depending on the fact if the number is positive or negative.

**Comment by grdw** [comment] 2016-06-21 12:17
> One thing to watch out for is that we now also have flexibility modelled in Merit 

I just talked to @jorisberkhout and flexibility is outside of the scope of this issue.

**Comment by antw** [comment] 2016-06-21 12:37
> Great! And than extend the Merit order plugin in ETEngine to make use of this new feature?

It can probably all be done in Merit, and exposed in ETEngine through Qernel::GraphApi [like the loss-of-load-expectation feature](https://github.com/quintel/etengine/blob/master/app/models/qernel/graph_api.rb#L97-L120) (i.e. it just makes a call to the appropriate class in Merit). Its good for this to be in Merit, rather than ETEngine, since it means it could potentially be reused [in other projects](https://github.com/quintel/merit-convergence) that also use the gem. [The plugin itself](https://github.com/quintel/etengine/blob/master/app/models/qernel/plugins/merit_order.rb) *probably* doesn't need changing since that's a helper to set up the merit order, and sets the results of the calculation in ETEngine.

[Merit::LOLE](https://github.com/quintel/merit/blob/master/lib/merit/lole.rb) is likely a good source of inspiration; hopefully it will be possible to create a similar API for excess events. Here's a *rough* idea for what I had in mind, but change it as you see fit. :grinning:

```ruby
# Takes a (calculated) merit order and the duration of "excess event" to look for
Merit::ExcessEvents.new(order, 1).call #=> 100

# or maybe
Merit::ExcessEvents.with(order, 2) # => 75

# And in ETEngine, something like:
#
# { 1 => Merit::ExcessEvents.with(order, 1),
#   2 => Merit::ExcessEvents.with(order, 2),
#   4 => Merit::ExcessEvents.with(order, 4),
#   8 => Merit::ExcessEvents.with(order, 8) }
#
# { 1 => 100, 2 => 75, 4 => 5, 8 => 2 }
```

**Comment by grdw** [comment] 2016-06-21 12:47
> Here's a rough idea for what I had in mind, but change it as you see fit

Yes, I have something in those lines. 👍

**Comment by grdw** [comment] 2016-06-22 08:40
@antw technical question:

I have two solutions to determine the 'total duration of excess events'. One is a ugly but fast way, the other is a nicer looking but slow (?) way. Anyway:

Attempt 1
````ruby
def number_of_events(duration)
  streak = 0

  possible_excess.each_with_index.inject(0) do |streak_count, (point, index)|
    peek = possible_excess[index.next] || 0

    if point > 0
      streak += 1

      if peek <= 0 || streak >= duration
        streak_count += 1
        streak = 0
      end
    end

    streak_count
  end
end
````

Attempt 2
````ruby
def number_of_events(duration)
  streaks = 0

  possible_excess.chunk { |x| x > 0 }.each do |_, chunk|
    if chunk.all? { |x| x > 0 } && chunk.size >= duration
      streaks += (chunk.size / duration)
    end
  end
  
  streaks
end


````

**Comment by antw** [comment] 2016-06-22 10:20
I like attempt 3 since the code looks cleanest, but it depends on the runtime. Is it much slower than attempt 1?

**Comment by grdw** [comment] 2016-06-22 10:23
Good question. I'll benchmark it.

**Comment by antw** [comment] 2016-06-22 10:55
BTW, attempt 3 doesn't need the `each` after the `chunk` (`chunk` returns a Enumerator, and `inject` will work fine on that). You can also avoid assigning to `result`, since the variable is thrown away at the end of the block:

```ruby
# ...
.inject(0) do |result, (excess_event, streak)|
  result + (excess_event ? (streak.size / duration) : 0)
end
```

**Comment by grdw** [comment] 2016-06-22 11:34
<img width="519" alt="screen shot 2016-06-22 at 13 33 49" src="https://cloud.githubusercontent.com/assets/2676542/16265149/fb2f2062-387d-11e6-8264-d58f13c561ae.png">

Attempt 1 is the first
Attempt 3 (+ your modifications) are the second.

This is for 2 Curve's with 8760 points.

**Comment by antw** [comment] 2016-06-22 12:00
Needs way more iterations to be meaningful. 😁 

I put together [a benchmark using benchmark-ips](https://gist.github.com/antw/2ffbc1e3f595e620f52e22f25d93055e):

```
Calculating -------------------------------------
      LONG_EVENTS Attempt #1    348.404  (± 3.2%) i/s -      1.768k in   5.079271s
     SHORT_EVENTS Attempt #1    351.339  (± 4.6%) i/s -      1.768k in   5.042061s
      LONG_EVENTS Attempt #3    464.217  (± 3.7%) i/s -      2.332k in   5.030536s
     SHORT_EVENTS Attempt #3    277.713  (± 4.3%) i/s -      1.404k in   5.065527s
```

Attempt 3 is fastest when the data is fairly constant (either long excess events, or long periods with no excess), but gets slower when there are frequent short excesses. The two algorithms are about equal when events average 5 hours in length.

Anyway, the worst case scenario is where each point flips from an excess to no excess (`[0.0, 1.0, 0.0, 1.0, ...]`), and attempt 3 can still do that ~180 times per second. I think that's more than good enough to make the cleaner code a better option.

**Comment by grdw** [comment] 2016-06-22 12:07
> Needs way more iterations to be meaningful. 

Yes it does. Thanks for making a nice benchmark. I need to remember that `ips` thingy.

**Comment by grdw** [comment] 2016-06-22 14:35
Some results:

For events that last 1 hour.
<img width="389" alt="screen shot 2016-06-22 at 16 32 34" src="https://cloud.githubusercontent.com/assets/2676542/16270559/07ff77b0-3897-11e6-86f5-23d4ed8d800f.png">

For events that last 2 hours:
<img width="395" alt="screen shot 2016-06-22 at 16 34 21" src="https://cloud.githubusercontent.com/assets/2676542/16270615/3e381134-3897-11e6-8c94-bb6f7d5b81ad.png">

For the present, the consumption is 0 this results in the `hours_per_year / excess_duration` result.

**Comment by jorisberkhout** [comment] 2016-06-22 14:51
Thanks for the good work so far, @grdw and @antw !

A short discussion with Gerard raised the following question: what is an excess event? (I am rephrasing the question for simplicity).

Take the following example of 10 consecutive hours, where 1 indicates excess electricity at that hour and 0 indicates no excess electricity at that hour.

`[1,1,0,1,0,1,1,1,1,0]`

### Interpretation 1

I would say that the number of excess events is **three**, one with duration = 1, one with duration = 2 and one with duration = 4. The table mentioned in the original post in this issue would then look like this:

| minimum duration (h) | # of events |
| --- | --- |
| 1 | 3 |
| 2 | 2 |
| 4 | 1 |

Interpreting the data like this tell the user how often there are period of excess electricity and how long they typically are.

### Interpretation 2

@grdw pointed out that you could also interpret the example (`[1,1,0,1,0,1,1,1,1,0]`) as having 7 excess events (i.e. 7 ones) and the table would then look like this:

| minimum duration (h) | # of events |
| --- | --- |
| 1 | 7 |
| 2 | 3 |
| 4 | 1 |

I feel very strong for my interpretation, but would like to hear the opinion of @grdw, @antw , @AlexanderWirtz,  @ChaelKruip and @dennisschoenmakers as well.

**Comment by antw** [comment] 2016-06-22 14:58
I think it depends on the definition of "event". Is it simply an excess of load (interpretation 2), or is it a *transition of state* from no excess to an excess, and back to no excess (interpretation 1)?

**Comment by jorisberkhout** [comment] 2016-06-22 15:04
> I think it depends on the definition of "event". Is it simply an excess of load (interpretation 2), or is it a transition of state from no excess to an excess, and back to no excess (interpretation 1)?

I would vote for transition, but am open to other opinions as well.

**Comment by antw** [comment] 2016-06-22 15:14
I agree that the word "event" implies that something has happened, and by that reasoning two consecutive hours of excess is only one event. One concern I have is that if you have a scenario in a state of constant excess, we would only show:

| minimum duration (h) | # of events |
| :---: | :---: |
| 1 | 1 |
| 2 | 1 |
| 4 | 1 |
| 8 | 1 |

... and that isn't very useful. That's an extreme scenario, but if you have a small number of very long events the table isn't going to help you understand what's going on.

Perhaps if we also showed the total duration of these events, it might be more helpful?

| minimum duration (h) | # of events | total duration of events |
| :---: | :---: | :---: |
| 1 | 1 | 8 days and 4 hours |
| 2 | 1 | 6 days and 2 hours |
| 4 | 1 | 2 days and 18 hours |
| 8 | 1 | 16 hours |

**Comment by antw** [comment] 2016-06-22 15:17
And just to mess things up with a third option... :grinning:

`[1,1,0,1,0,1,1,1,1,0]`

| duration (h) | # of events |
| :---: | :---: |
| 1 hour | 1 |
| 2 to 3 hours | 1 |
| 4 to 7 hours | 1 |
| 8 or more hours | 0 |

`[1,0,0,1,0,1,1,1,1,0]`

| duration (h) | # of events |
| :---: | :---: |
| 1 hour | 2 |
| 2 to 3 hours | 0 |
| 4 to 7 hours | 1 |
| 8 or more hours | 0 |

**Comment by jorisberkhout** [comment] 2016-06-22 15:58
I like that 3rd option a lot, @antw . One thing it doesn't do is communicate how many excess events of a minimum length there are in total, but I guess our users are smart enough to add the entries they are interested in.

**Comment by grdw** [comment] 2016-06-23 07:41
> [..] but I guess our users are smart enough to add the entries they are interested in.

What do you mean by 'add'? Is the table going to be flexible? 

About the interpretations.

> I feel very strong for my interpretation, but would like to hear the opinion

I get what you mean. My interpretation counts events some events twice. So in essence:

````
[1,1,0,1,0,1,1,1,1,0]
 \ /   |    \   /
  2    1      4
````

In total 7 events that last 1 hour, 3 events that last 2 hours, 1 event that lasts 4 hours. The problem is that if you have this in one table it can be seen as though the 'net load' looked liked:

````
[1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,0,1,1,0,1,1,0,1,1,1,1]
 \                         /\                /\      /
     7 events of 1 hour           3 of 2       1 of 4
````

This is ofcourse not what you want the table to say. 

--

About @antw third interpretation. Doesn't it matter exactly how long a certain excess event lasts? I'm a bit wondering if it's justified to group them into 2-3 hours, 4-7 hours, etc.?

--

So I'm a bit more leaning towards Joris's first interpretation with the total duration of events included.

**Comment by jorisberkhout** [comment] 2016-06-23 09:32
@ChaelKruip suggested to display the data as a chart rather than a table. This chart would look something like this.
 
<img width="604" alt="screen shot 2016-06-23 at 11 28 09" src="https://cloud.githubusercontent.com/assets/4669028/16298413/98348ff2-3935-11e6-938d-5c6ecbd207d2.png">

As discussed it makes sense to display events with a minimum duration from 1 to 24 hours. 

Would it be possible to make this chart, @grdw ? You can look at the `Merit order capacities and marginal costs` chart for inspiration.

I would like the `V(GRAPH(), number_of_excess_event(duration)` function to remain available in the Sandbox.

**Comment by grdw** [comment] 2016-06-23 09:43
> Would it be possible to make this chart, @grdw ? You can look at the Merit order capacities and marginal costs chart for inspiration.

Everything is possible but I'm just wondering how practical this is to implement. I'm going to take a technical look and I'll let you know in the comments.

I think it would be ok to leave the `number_of_excess_events` in etengine. In merit I'd have to create another method that takes a set of time groups (please correct me on my variable naming) and returns the amount of events for those time groups.

So in essence:

````ruby
def events_groups(time_groups = [])
  time_groups.map do |time|
    [time, number_of_events(time)]
  end
end
````

In ETEngine there has to be another method that calls the `event_groups` method. 

Than in ETModel there has to be another `output_element`, in the form of a D3Chart. Maybe we can re-use an existing bar-chart? And there needs to be one `output_element_serie` for this chart for which we need to write a GQL in `etsource`. If I'm fully correct?

**Comment by grdw** [comment] 2016-06-23 09:46
> number_of_excess_event(duration) function to remain available in the Sandbox.

Are we clear about what that method in itself must return? 😆

**Comment by jorisberkhout** [comment] 2016-06-23 09:50
> Are we clear about what that method in itself must return? 😆

Yes, `V(GRAPH(), number_of_excess_event(duration)` should return the number of times in the year where there is excess electricity for **at least** [duration] number of hours.

**Comment by grdw** [comment] 2016-06-23 11:38
@jorisberkhout I think @ChaelKruip also pointed out, that if your event last longer than 24 hours tehre needs to be one extra bar which is `> 24` but I consider this to be a nice to have, because I'm thinking the odds of that are pretty low. But I'd like to know your opinion about it aswell.

**Comment by jorisberkhout** [comment] 2016-06-23 11:55
> @jorisberkhout I think @ChaelKruip also pointed out, that if your event last longer than 24 hours tehre needs to be one extra bar which is > 24 

Correct, but these events are included in the bar for `24 hours` as these bars indicate the number of events with a minimum duration of 24 hours.

**Comment by grdw** [comment] 2016-06-23 15:41
<img width="616" alt="screen shot 2016-06-23 at 17 41 14" src="https://cloud.githubusercontent.com/assets/2676542/16309626/b66327c0-3969-11e6-95ae-bba08eb03f17.png">

This is the first edition. Feast your eyes on this beauty.

**Comment by jorisberkhout** [comment] 2016-06-23 15:42
:heart::heart::heart::heart::heart::heart::heart::heart:

**Comment by grdw** [comment] 2016-06-24 12:36
Major status update:

- I made a GQL which is over [here](https://github.com/quintel/etsource/pull/1138)

One question for @antw or anyone else that feels like he knows the answer. Is it allowed to do the `(0..24).to_a` trick or do I need to type out `[1,2,...23,24` style-wise? I have the feeling that I'm sort of breaking a rule in a style-guide.

- I also created the [small bits](https://github.com/quintel/etengine/pull/850) of ETEngine necessary to handle the [changes in merit](https://github.com/quintel/merit/pull/141). 

About that, is it okay to use method chaining in this context or might there be a better solution to exclude participants from the Excess calculation.

In ETModel there's currently a stable chart. There are some nitpicky things which I don't like. For instance the `transitions` feel a bit useless and a bit tedious to look at. The chart is now 'flipping in from below' (for people interested you can check my screen). I did manage to fix #2157 in the process. 

Also there are bunch of translations still missing and I'm not sure about the formatting of the table values which now look pretty 'blank':

<img width="608" alt="screen shot 2016-06-24 at 14 35 34" src="https://cloud.githubusercontent.com/assets/2676542/16337868/f1efd798-3a18-11e6-8676-92ba4f10b3af.png">

Also, must we show events higher than 24 hours? I remember @ChaelKruip having an opinion about it but I'd like to hear the rest as well: @antw @jorisberkhout

**Comment by jorisberkhout** [comment] 2016-06-24 13:07
> Also, must we show events higher than 24 hours?

These events are included in bin `24`, as these bins represent the **minimum** duration of an excess event, i.e. bin `24` contains all events that last at least 24 hours.

**Comment by antw** [comment] 2016-06-24 14:06
> Is it allowed to do the (0..24).to_a trick or do I need to type out [1,2,...23,24] style-wise? I have the feeling that I'm sort of breaking a rule in a style-guide.

I think it's fine. It requires the reader to know a bit about Ruby, but there are lots of examples of Gqueries dropping down to plain Ruby when makes something easier or cleaner. Glad you're thinking about this sort of thing, though. :+1:

> About that, is it okay to use method chaining in this context or might there be a better solution to exclude participants from the Excess calculation.

I think `excludes` would be better just passed into the `Excess` constructor, it's not really something which should change after the `Excess` is initialized.

```ruby
graph.plugin(:merit).order.excess(excludes: array).number_of_events(*args)
```

**Comment by jorisberkhout** [comment] 2016-06-24 14:23
@grdw, would it be possible to remove the legend for this chart? Since this chart will only ever contain one series, this legend doesn't add much information. (I mean the thing in the red box::)

<img width="616" alt="b66327c0-3969-11e6-95ae-bba08eb03f17" src="https://cloud.githubusercontent.com/assets/4669028/16340344/f8a09bb8-3a27-11e6-9be1-292305ec1558.png">

**Comment by grdw** [comment] 2016-06-24 14:27
> it's not really something which should change after the Excess is initialized.

Yes, makes sense. That was my second option though 👍 

> would it be possible to remove the legend for this chart?

Yes 👍 removing things is my specialty,

**Comment by jorisberkhout** [comment] 2016-06-24 14:29
> Yes 👍 removing things is my specialty,

I'll remove the translations for the legend as I am working on those ATM.

**Comment by grdw** [comment] 2016-06-24 14:30
> I'll remove the translations for the legend

![remove all of it](https://cdn.meme.am/instances/500x/55559546.jpg)

Btw, comment nr 50 is a fact.

**Closed** 2016-06-30 09:58 UTC
