### ISSUE TITLE
'Storage in reservoirs' should not be shown when `has_mountains = false`

### ISSUE THREAD

**Issue by marliekeverweij** [quintel/etmodel#2971] opened 2019-02-13 08:52 UTC
In the Dutch dataset `has_mountains = false` but the 'Storage in reservoirs' is shown in the flexibility options list. Is it possible to hide it?

![screen shot 2019-02-13 at 09 47 24](https://user-images.githubusercontent.com/32833996/52698913-d6533580-2f74-11e9-9878-d2fae1854e98.png)

**Comment by michieldenhaan** [comment] 2019-02-14 11:30
Closing, duplicate of https://github.com/quintel/etmodel/issues/2889

**Closed by michieldenhaan** 2019-02-14 11:30 UTC
